### ISSUE TITLE
OpenGraph support

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#673]
# Initiative
Improve the SEO support and settings of the onOffice for WP-Websites Plugin.

### Epic
Implement OpenGraph support.

### User story 
As a real estate agent utilizing the onOffice for WP-Websites Plugin, I aim to enhance the visibility and appeal of my property listings on social media platforms. Currently, the plugin lacks native support for OpenGraph and Twitter Card data, necessitating the use of third-party SEO plugins. I request the implementation of integrated OpenGraph and Twitter card support within the plugin.

- OpenGraph Data integration: Develop functionality to automatically generate essential OpenGraph metadata such as "og:title: from title of the property in onOffice enterprise", "og:description: Description from the property in onOffice enterprise", "og:image: from enterprise images ( be aware of further meta properties of the og:images)", "og:type: website", "og:url: URL of the domain (with and without "speaking" URL)", "og:locale", "og:site name" based on property information.
- Twitter Card Integration: Extend support for Twitter Cards by automatically generating "twitter:title", "twitter:description" and "twitter:image" with relevant property details.
- Toggle option for automatic data generation: Implement a user-friendly option within the plugin settings to toggle the automatic generation of OpenGraph and Twitter Card data. This feature allows users to turn it on or off according to their preferences.
- Dynamic PHP variables: Ensure the generated OpenGraph and Twitter Card data dynamically pulls information from PHP variables related to each property, ensuring accuracy and relevance.

OpenGraph: https://ogp.me/

By implementing this feature, the onOffice for WP-Websites Plugin can provide real estate agents with an integrated solution for generating accurate and dynamic OpenGraph and Twitter Card datam enhancing the visual appeal and shareability of property linstings on social media platforms.

### Tasks

- [x] Develop logic to automatically generate the OpenGraph and Twitter Card metadata based on relevant property details.
- [x] Ensure that the generated OG and Twitter Card data dynamically pulls information from PHP variables related to each property.
- [x] Integrate necessary modifications to the backend settings interface to accomodate the new OpenGraph and Twitter Card support.
-- Toggle option that  allows users to turn the automatic generation of OG and Twitter Card data on and off in case they want to use a third party SEO Plugin.
- [x] Conduct  thorough testing to ensure seamless functionality under different conditions and property types.
- [x] Implement Twitter:images (currently blocked)

**Comment by yeneastgate** [comment]
> * -- Toggle option that  allows users to turn the automatic generation of OG and Twitter Card data on and off in case they want to use a third party SEO Plugin.

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/21eface6-dcac-4148-9a41-724ce89d9346)

@fredericalpers Do you want me to implement a "toggle option" like the image below?

**Comment by fredericalpers** [comment]
@yeneastgate yes! please go ahead and implement this as the toggle option :)

**Comment by yeneastgate** [comment]
> @yeneastgate yes! please go ahead and implement this as the toggle option :)

@fredericalpers I need 4 days to implement and test it

**Comment by dai-eastgate** [comment]
> * "og:locale", "og:site name" based on property information.

**_1. "og:locale" based on property information_**
=> Do you mean to display "map location of details estate"(based on longitude and latitude) for the "content" attribute for "og:locale" tag?
ex: map location of details estate: Gnutz is in Germany (locale: de_DE) => <meta property="og:locale" content="de_DE">

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/d529d954-519f-4af9-8b0b-4e27ffe5dab6)

**My Suggest:** Normally, third-party plugins (ex: Rank Math SEO and Yoast SEO), are taken according to the language the website supports.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/0181440a-77ae-4783-bb53-4c531bcb584c)

**_2. "og:site name" based on property information._**
=> Can you explain specifically the information Which you want to display for the "content" attribute for the "og:site_name" tag?

**My Suggest:** Normally, 3rd party plugins (Rank Math SEO and Yoast SEO)

**- Rank Math SEO:** https://rankmath.com/kb/open-graph-meta-tags/
"site_name": get "site title" in WP settings. 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/2aeb31e9-c9ae-4dd3-8624-d1cebb979d32)

**- Yoast SEO:** https://yoast.com/help/website-name-alternate-website-name-and-alternate-organization-name/
"site_name": get "site title" in WP settings.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/6ed6ec41-1f43-4388-83d6-9c3efdb12501)

**Comment by dai-eastgate** [comment]
> * "og:image: from enterprise images ( be aware of further meta properties of the og:images)"
@fredericalpers 
1. **Do you mention "og:image:height" and "og:image:width"?**
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8d0ebd2e-4d67-4943-96e4-d4e8e793ecf9)

**Note:** I found recommendations for the "og:image" tag:
**_Open Graph:_** 
min: og:image:height = 200, og:image:width = 200
max: og:image:height = 1200, og:image:width = 630
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/d908b13b-b77a-44dd-9456-19ba0b5efefd)

**_Twitter Card:_** 
min: twitter:image:height = 300, twitter:image:width = 157
max: twitter:image:height = 4096, twitter:image:width = 4096
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/4c1351b6-5a22-483c-83ff-bdbe79b2b1f8)

=> Do you want to implement the recommended sizes for "og:image:height" and "og:image:width"?

**2. Block:** "The image is not displayed when sharing links on Twitter."
**Cause:** URL (URL image in onOffice enterprise) used for the "content" attribute of "og:image" tag is not passing Twitter's validator card
ex: 
**- URL in onOffice enterprise:** 
https://image.onoffice.de/smart25/Objekte/index.php?kunde=MAT-TRAFFIC&datensatz=559&filename=83fad556-ffbb-42a2-8a6f-1d5d25917d2c.jpg 
**- This is the link response of the API result:** 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/a690d8c4-ebac-4e98-917c-f284286b353f)

**- Card validator of Twitter**: https://cards-dev.twitter.com/validator
**- Result from check validate:** ERROR: Fetching the page failed because it's denied by "robots.txt".
=> I need more time to check the solution to this block by robots.txt and respond to you the results investigation as soon as possible.

**Comment by fredericalpers** [comment]
> 1. "og:locale" based on property information
You are right, this is a mistake on my end. This should be set by the websites language.

> 2. "og:site name" based on property information.
You are right, this is a mistake on my end. This should be set by the websites title.

> Do you mention "og:image:height" and "og:image:width"?
Yes, I'm talking about all related meta properties of the og:image tag. Please go ahead and use the recommended widths and heights.

> Block: "The image is not displayed when sharing links on Twitter."
I'm assuming this is something we can not fix then unless the robots.txt will be changed on the file hosting server?

**Comment by dai-eastgate** [comment]
> You are right, this is a mistake on my end. This should be set by the websites language.



> You are right, this is a mistake on my end. This should be set by the websites title.



> Yes, I'm talking about all related meta properties of the og:image tag. Please go ahead and use the recommended widths and heights.

@fredericalpers I got it, thanks!



> I'm assuming this is something we can not fix then unless the robots.txt will be changed on the file hosting server?

I'll find out more and let you know soon

**Comment by dai-eastgate** [comment]
@fredericalpers 
I have implemented Open Graph and Twitter Card integration into the onOffice plugin:

1. For Open Graph:

 + og:title: OK
 +  og:description: OK
 + og:image: OK
 + og:type: OK
 + og:url: OK
 + og:locale: OK
 + og:site name: OK

2. For Twitter Cards:

 + twitter:title: OK
 + twitter:description: OK
 + twitter:image: Block because of robots.txt

Please take a look at my video demo and let me know your opinion about this. Thanks! 

https://files.fm/u/wcqczwuwyt#/view/uhmfrzzp56

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! this feature will make a lot of customers very happy :)

I will send a ticket about the blocking of twitter:image through the robots.txt to our IT-Department and update you as soon as possible.

**Comment by fredericalpers** [comment]
@dai-eastgate we want to implement everything even though the robots.txt might still be blocking the twitter:image, so that as soon as the robots.txt is changed the images will work.
