### ISSUE TITLE
Search field for field lists

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#674]
# Initiative
Improve the usability of the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Implement a Search field for field lists.

### User story

As a real estate agent utilizing the onOffice for WP-Websites Plugin, I find the current backend settings for property lists and forms to be complex with numerous field options distributed across different categories. Navigating through these settings is challenging, especially when trying to locate specific fields to add to my property lists or forms. To enhance the usability I request the implementation of a search field. This search field will enable me to efficiently search for and add the fields I need, simplifying the configuration process.

- Introduce search field: Add a search field above the field list for property lists, detail view, similar estates, unit lists, forms and address lists.
- Universal search functionality: Ensure that the search field has universal functionality, allowing me to search for fields across all available categories.
- Instant filtering/Search completion and suggestions: Implement instant filtering as I type in the search field, dynamically narrowing down the available options based on the entered search term.
-- The search should not be case sensitive so that lower and upper case makes no difference
-- It should be possible to complete the input - e.g.: when entering "Hau", Hausgeld, Hausnummer, Haustiere, Dist. Hauptschule (km)  should be displayed as suggestions. If "Haus" is entered, only Hausgeld, Hausnummer und Haustiere should appear accordingly. If "Hausg" is entered, only Hausgeld should appear.
- Clear field labels: Display the category and field name for each field to assist in quickly identifying the desired options during the search.
- Selection and Addition: Enable a seamless selection and addition process, allowing me to add the desired fields to my property lists or forms directy from the search results.

Select2: https://select2.org/searching

By implementing this search field feature, the onOffice for WP-Websites Plugin can significantly enhance the user experience for real estate agents, making it more efficient to configure property lists and forms by quickly locating and adding the desired fields.

### Tasks

- [x] Develop and implement te search field within the settings above the fieldslists. See screenshots attached.
- [x] Implement instant filtering logic / completion / search suggestions logic, allowing users to search across all available categories and fields. Dynamically updating the available options based on the entered search term in real-time. See above.
- [x] Ensure that the category and fieldnames are displayed for each field, aiding users in quickly identifying the desired options during the search.
- [x] Implement responsive design for the search field and associated functionalities, ensure a consistent user experience across different devices and screen sizes.
- [x] Implement highlighting for search results, making it visually clear for users to identify matched fields withing the extensive list of options.
- [x] Conduct rigorous testing of the search field functionality, including positive and negative test cases to ensure its reliability and performance.

**fieldlist searchfield:**
![fieldlist_searchfield](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/85a45432-8344-4823-bcf4-90470909f3fa)

**fieldlist results 1**
![fieldlist_results1](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/0bdb868d-f126-44a6-abe0-5cdf1435649e)

**fieldlist results 2**
![fieldlist_results2](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/df29a0c3-3148-4cbc-af11-ab2719082a99)

**Comment by dai-eastgate** [comment]
@fredericalpers In case the user has not entered text to search, how will the data of the "box field search" be displayed?
Will the dropdown be displayed as autocomplete or displayed as shown below?

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/dede1739-1c16-4026-b2fd-c0386c9fabaa)

**Comment by fredericalpers** [comment]
@dai-eastgate if the user did not input any text the dropdown should be displayed as in the screenshot. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers I need 7 days to fix and test it. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers 
I have implemented the "Search Field" feature for 9 screens (address list, estate list, detail view, similar estate, unit list, contact form, interest form, owner form, and applicant search form) according to the following modules:
1.Without entering a search keyword, if the user focuses on "input search", the dropdown will display all fields.

2.Search by text
-Search by "field" name, "category" name, "key of field" name
-Search is not case sensitive
-Search by suggested keywords

3."Clear search input"  feature (icon "X" in "input search")

4.Feature "add field" (icon "+") and "remove field" (icon "-") in "box search"

5.Highlighting for search results (if the field has been added to the field config, the "-" icon is red)

Please take a look at my video demo and let me know your opinions. Do you need to add anything more about this search feature?

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/19795400-eb72-4cc1-be3f-80edd117e6db

**Comment by fredericalpers** [comment]
@dai-eastgate seems to be working fine :) thank you
