### ISSUE TITLE
Adaptive image resolution

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#675]
# Initiative
Improve the accessibility and performance of the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Implement adaptive image resolution.

### User story
As a real estate agent utilizing the onOffice for WP-Websites Plugin, Iam concerned about the impact of image presentation on my website's SEO and pagespeed. Currently, the plugin loads images uniformly in one size as background images, which may hinder performance and SEO rankings. To address this, I require the implementation of a feature that utilizes the HTML picture-tag and srcset attribute for images, allowing for responsive image handling. This enhancement aims to improve pagespeed and SEO, providing a faster and more optimized website for a better user experience and search enging ranking.

The current method of loading images as background images in a uniform size may contribute to slower page loading times and suboptimal SEO performance. To address these concerns, I propose the following enhancements:

- Responsive image implementation: Integrate the HTML picture-tag and srcset attribute to enable the plugin to load images responsively based on device characteristics, such as screen size and resolution.
- Multiple image size: Dynamically load the most appropiate size based on the users device, enhancing both pagespeed and the user experience.
- SEO friendly Alt text: Ensure that each image withing the picture-tag is accompanied by SEO-friendly alt text, improving the website's accessibility and search enginge visibility.
- Lazy loading support: Integrate lazy loading functionality for images to defer the loading of off-screen images, further optimiing pagespeed.

By implementing these enhancements, the onOffice for WP-Websites plugin can significantly improve the websites pagespeed and SEO performance, offering real estate agents a competitive advantage in providing a fast, responsive and search enginge-friendly online presence. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

### Tasks

- [x] Modify the image handling code to incorporate the HTML <picture> tag and srcset attribute
- [x] Implement the following width values min-w 1600, min-w 1400, min-w 1200, min-w 992, min-w 768, min-w 576, max-w 575
- [x] Ensure that each image within the picture-tag is accompanied by an alt-tag. Populate the alt text with the property title within onOffice enterprise. Make sure its possible to overwrite those with SEO plugins such as Yoast etc.
- [x] Integrate lazy loading for images

**Comment by dai-eastgate** [comment]
@fredericalpers 
> * Modify the image handling code to incorporate the HTML  tag and srcset attribute
> * Implement the following width values min-w 1600, min-w 1400, min-w 1200, min-w 992, min-w 768, min-w 576, max-w 575

Do you want me to implement a structure like this? And please provide me the image width according to each screen size(min-w 1600, min-w 1400, min-w 1200, min-w 992, min-w 768, min-w 576, max-w 575)
``` 
echo '<picture>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 350])) .'" media="(min-width:1600px)"/>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 300])) .'" media="(min-width:1200px)"/>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 280])) .'" media="(min-width:992px)"/>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 325])) .'" media="(min-width:768px)"/>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 360])) .'" media="(min-width:576px)"/>';
     echo '<source srcset="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 575])) .'" media="(max-width:575px)"/>';
     echo '<img class="adaptive-image estate-status"
            src="'. esc_url($pEstatesClone->getEstatePictureUrl($id, ['width' => 350])) .'"
            alt="'. esc_html($currentEstate["objekttitel"]) .'"
            loading="lazy"
      />';
echo '</picture>';
```
> * SEO friendly Alt text: Ensure that each image withing the picture-tag is accompanied by SEO-friendly alt text, improving the website's accessibility and search enginge visibility.

"alt text": is a "property title", right?

Currently, I check that the background size is being applied to these screens. Do you want me to fix it on these screens?
- Estate list 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8567f613-70af-4293-ad78-4d72d1bac947)
- Detail view 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/445332c9-de8b-49dc-9d6c-901014b67ab7)
- Similar estate 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/819721e3-b17a-4b88-af73-ef2c808b279a)

**Comment by yeneastgate** [comment]
@fredericalpers I need time to check it and will let you know soon.

**Comment by dai-eastgate** [comment]
@fredericalpers 
1. Do you want to implement "a picture tag" html as below?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/764dfef2-a853-433c-825e-c1c742223c01)

2. Currently, I check and see that on the plugin "method of loading images as background images" is used in the following 3 screens:
- Estate list:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/64c080e0-7c64-4380-acc0-cf88eb0e98d3)
Currently, I see you are fixing the CSS for the default height equal to 250px
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/6b9338e3-4f1b-4f4b-bd3f-0b35c468d276)
=> Please confirm for me that the "uniform size" displayed for the image here has a height equal to 250px, right?

- Estate detail
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/bacaaacc-c9dc-4c6c-a3c5-857bedaf4ff4)
Currently, I see you are fixing the CSS for the default height equal to 400px
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/eee43c9f-c013-407b-ad86-43b0de45b9c8)
=> Please confirm for me that the "uniform size" displayed for the image here has a height equal to 400px, right?

- Similar estate
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/ec365488-9621-4966-b299-154103bd7fe8)
Currently, I see you are fixing the CSS for the default height equal to 250px
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/73ca74d2-18ff-4be0-b6ba-b1ea27b1fd19)
=> Please confirm for me that the "uniform size" displayed for the image here has a height equal to 250px, right?

**Comment by dai-eastgate** [comment]
> * => Please confirm for me that the "uniform size" displayed for the image here has a height equal to 250px, right?

@fredericalpers Please reply so I can estimate the time for this issue. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate 
> Do you want to implement "a picture tag" html as below?

yes, but please also implement the different image sizes in the srcset aswell, i.e. for 1x, 1.5x, 2x and 3x. As an example:
`<source media="(min-width: 1400px)" srcset="http://bild.jpg 1x, http://bild.jpg 1.5x, http://bild.jpg 2x, http://bild.jpg 3x">`

> Please confirm for me that the "uniform size" displayed for the image here has a height equal to 250px, right?

The image height 250px for property lists is correct.

> Please confirm for me that the "uniform size" displayed for the image here has a height equal to 400px, right?

The image height 400px for the property detail page is correct.

**Comment by yeneastgate** [comment]
@fredericalpers 
1. I have implemented "Integrate the HTML picture-tag" for these screens:
Estate List:  https://files.fm/u/punfusqdu9#/view/dmnjd8ec69
Detail View:  https://files.fm/u/punfusqdu9#/view/tm4n55ttm5
Similar Estate:  https://files.fm/u/punfusqdu9#/view/sa8adhs9zr

2. I have implemented the following width values min-w 1600, min-w 1400, min-w 1200, min-w 992, min-w 768, min-w 576, max-w 575

3. 

> * Ensure that each image within the picture-tag is accompanied by an alt-tag. Populate the alt text with the property title within onOffice enterprise

=> I have displayed the "alt-tag" of "<img />" HTML with the property title within onOffice enterprise"




> * Make sure its possible to overwrite those with SEO plugins such as Yoast etc.

=> Can you tell me how to overwrite the "alt-tag" of "<img />" HTML using "Yoast SEO"?

I have read Yoast SEO's documentation. And I only found how to overwrite the "alt-tag" of "<img />" HTML for images Which were uploaded on the "Media" menu dashboard of the admin backend. 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/5092d5c3-cd3f-4543-9f1f-81bb7f92f892)
For "our images" Which are returned by the API onOffice, these images will not be supported.

I also tried another plugin that can overwrite the "alt-tag" of "<img />" HTML. That plugin is named "BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce". 
You can see how I test overwrite "alt-tag" of "<img />" html with this plugin.
https://files.fm/u/punfusqdu9#/view/rph2fwbb3b
Could you please confirm that my test is correct for the desire you mentioned?

4.  I have implemented "Integrate lazy loading for images"

**Comment by fredericalpers** [comment]
@yeneastgate sorry for the confusion. Overwriting the alt-tags can be ignored, as you are right it only applies to pictures uploaded to "media".

Everything else seems to be working fine, thank you :)
