### ISSUE TITLE
Show number of published properties

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#699]
# Initiative
Optimize the backend of the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Show the number of published properties.

### User story
As a real estate agent utilizing the onOffice for WP-Websites plugin, I often manage multiple property lists on my website to present diverse real estate options. Currently there is no indication in the plugin backend regarding the total number of properties published through each property list and its associated filters. To enhance transparency and facilitate effective property list management, I propose the implementation of a feature that displays the count of published properties for each list in the plugin backend.

The current lack of visibility into the number of published properties for each property list hinders efficient management and understanding of the impact of applied filters and if any properties are published at all.

### Tasks

- [x] Enhance the property lists detail settings with a visual indicator for the count of published properties in the Box Filter & Records
- [x] Ensure seamless integration with the onOffice enterprise API to retrieve real-time information on the number of published properties
- [x] If applicable, extend the feature to display counts based on specific filters applied to each property list

By implementing this feature the onOffice for WP-Websites Plugin can empower real estate agents with valuable insights of each property list, facilitating a streamlined management of their offerings.

**Comment by dai-eastgate** [comment]
@fredericalpers I found a solution to be able to "Show number of published properties" in the "Box Filter & Records" of the Estate List
-Note: Even though I tried to optimize the number of API calls as much as possible, BE's performance in "edit list view" still increased significantly (about 17%).
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/a459dd56-f6b0-4722-89f3-6a07e2ef82ff)
Please give me your opinion on the above issue. If you agree, I will continue implementing

**Comment by fredericalpers** [comment]
@dai-eastgate I will have to get feedback from my colleagues on this one. I'm not sure if the "benefits" outweigh the worse performance. Thank you :)

**Comment by fredericalpers** [comment]
@dai-eastgate after discussing this we would like to make some changes because of the performance issue.

Instead of always displaying the amount of published properties, we would like to add a button for checking if and how many properties are published. This way the API calls should only be made when using the button. If 0 published properties are found there should be a quick explanation as to why this can happen with a link to our [plugin setup documentation](https://wp-plugin.onoffice.com/de/erste-schritte/einrichtung/).

**Comment by dai-eastgate** [comment]
@fredericalpers OK, I got it. I will investigate and let you know my solution. Thanks!

**Comment by dai-eastgate** [comment]
> we would like to add a button for checking if and how many properties are published. This way the API calls should only be made when using the button.

@fredericalpers I have tried to implement this idea. Please watch my demo video: 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/6114a060-4525-4a56-956b-6f629044e1cf

Do you agree with my solutions and User Interface (UI)?

**Comment by fredericalpers** [comment]
@dai-eastgate idealy there would be only one button at the bottom of the "filters & records" box to show published properties. Is this something you can change?

**Comment by dai-eastgate** [comment]
> @dai-eastgate idealy there would be only one button at the bottom of the "filters & records" box to show published properties. Is this something you can change?
@fredericalpers 
I got it. I will try it and respond to you asap.

**Comment by dai-eastgate** [comment]
@fredericalpers Please watch my video demo and let me know your opinion. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f4e5d867-af33-4225-b6d9-7ab79a5fab8d

**Comment by fredericalpers** [comment]
Looks good to me! Thank you :)

**Comment by fredericalpers** [comment]
decided against the feature because the poorer performance does not reflect the benefit.
