### ISSUE TITLE
Energy certificate data on detail pages

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#718]
# Initiative
Improve the onOffice for WP-Websites plugin usability

### Epic
Add energy certificate fields automatically to new detail page

### User story
As a real estate agent operating within the European Union, I am obligated by law to provide specific energy certificate information for each property listing on my website. However, the onOffice for WP-Websites Plugin currently lacks the feature to automatically add the mandatory fields when setting up a new detail page. To ensure compliance with regulations and streamline the property listing process, I propose the automatic inclusion of these fields during the creation of a new detail page.

The absence of automatic inclusion for mandatory fields during the setup of a new detail page results in additional manual work fpr real estate agents and increases the risk of overlooking essential information required by EU regulations. To address this, the onOffice Plugin should automatically add those required fields upon setting up a new detail page.

### Tasks
- [x] Compile a list of fields required for energy certificate information in accordance with EU regulations (See details)
- [x] Integrate functionality into the onOffice plugin to automatically add the mandatory fields when a new detail page is created
- [x] Ensure that fields that are disabled or unavailable in enterprise due to country specific differences do not generate errors. E.g. Austria and Germany. (See details)

By automating the addition of mandatory fields for new detail pages, the onOffice for WP-Websites Plugin can significantly reduce workload for real estate agents, ensure compliance with EU regulations and enhance the efficiency of the property listing process.

### Energy certificate mandatory fields
<details><summary>Details</summary>
<p>

| DE / Germany and rest of EU |
|--------|
| the type of certificate (energieausweistyp) |
| the final energy rating of the property in kWh/m²a (endenergiebedarf and energieverbrauchskennwert) |
| the (main) energy source for heating (energietraeger) |
| the year of construction of the building (baujahr) |
| the efficiency class of the property (energyClass) |
| the level of CO2 emissions of the building for newly issued energy performance certificates after 01.05.2021 (co2ausstoss and co2_Emissionsklasse) |

</p>

<p>

| AT / Austria|
|--------|
| Heating requirement - HWB (ea_hwb_at) |
| the final energy rating of the property in kWh/m²a (ea_hwb_klasse_at) |
| the (main) energy source for heating (energietraeger) |
| the year of construction of the building (baujahr) |
| the efficiency class of the property (ea_fgee_klasse_at and ea_fgee_at)|
| the level of CO2 emissions of the building for newly issued energy performance certificates after 01.05.2021 (co2ausstoss and co2_Emissionsklasse) |

</p>

<p>

| ITA / Italy|
|--------|
| the type of certificate (energieausweistyp) |
| the final energy rating of the property in kWh/m²a for Residential properties and in kWh/m³a for Commercial properties (endenergiebedarf and energieverbrauchskennwert) |
| the (main) energy source for heating (energietraeger) |
| the year of construction of the building (baujahr) |
| the efficiency class of the property (energyClass) |
| the level of CO2 emissions of the building for newly issued energy performance certificates after 01.05.2021 (co2ausstoss and co2_Emissionsklasse) |

</p>

</details>

**Comment by fredericalpers** [comment]
@dai-eastgate please go ahead and implement it for the site language setting.

The various fields are only available anyway if onOffice enterprise is set to the respective language or if they are specifically activated withing onOffice enterprise. E.G. HWB (ea_hwb_at) for Austria will only be available if onOffice enterprise is set to German (Austria) and not available when set to German (Germany) or Italian.

**Comment by dai-eastgate** [comment]
@fredericalpers I got it.

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented for the site language setting. Please watch my video demo and let me know your opinions. Thanks! 
https://files.fm/u/xhrhgjcbdj#/view/dz867dx3x3

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! thank you :) is this ready to be labeled as in review?

**Comment by dai-eastgate** [comment]
> @dai-eastgate looks good to me! thank you :) is this ready to be labeled as in review?

Yes, please help us to review.
