### ISSUE TITLE
Caching duration setting

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#720]
# Initiative
Improve the onOffice for WP-Websites Plugin usability

### Epic
Implement caching duration setting

### User story
As a real estate agent managing a dynamic and frequently updated website, I find the current caching period of 1 hour in the onOffice for WP-Websites Plugin restrictive. To adapt to  varying update frequencies and ensure that the latest property information is consistently reflected on my website, I require the ability to customize the caching duration according to my specific needs.

The onOffice plugin currently imposes a fixed caching of 1 hour, meaining that property information is refreshed at set intervals unless the cache is manually cleared. However, this might not align with the updated frequency of property data in my property portfolio. To address this limitation, I propose the introduction of a customizable cache duration feature that allows me to set the caching period to a time frame that suits the dynamics of my property listings.

### Tasks

- [x] Enhance the plugin settings interface to include an option for configuring the caching duration. (See screenshot below)
- [x] Integrate the feature into the backend in the settings of the onOffice plugin. 10min, 30min, 1h (this should still be the default), 6h, 12h, 24h.
- [x] Integrate a information text explaining the cache / cache duration. See below.

**DE:** Der Wert Cache-Laufzeit bestimmt, nach welchem Zeitraum der Plugin-Cache deiner Seite neu befüllt wird. Dieser Wert steht standardmäßig auf 1 Stunde.

**EN:** The Cache duration value determines the period of time after which the plugin cache of your page is refreshed. This value is set to 1 hour by default.

By providing the option to customize the caching duration, the onOffice for WP-Websites Plugin can offer real estate agents greater flexibility and control over how frequently property information is updated on their websites. This customization ensures that the plugin accomodates a variety of use cases and aligns with the diverse needs of real estate professionales.

![Caching-Duration-setting](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/a5ba0fc6-cc1a-4e30-b248-2c6508384f8a)

**Comment by dai-eastgate** [comment]
@fredericalpers I need a day to implement and test it. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented the cache duration settings. Please watch my video demo and let me know your opinions.
https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8445bd4b-1328-454d-9ec2-4c70673c645f

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! this is ready to be labeled as in review?

**Comment by dai-eastgate** [comment]
@fredericalpers Yeah sure, Please help us to review it. Thanks!
