### ISSUE TITLE
Thousand separator in form inputs

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#721]
# Initiative
Improve numeric form inputs in the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Implement thousand separators in frontend display for numeric form inputs.

### User story
As a real estate agent utilizing the onOffice for WP-Websites plugin, I find that form inputs containing numerical values, such as buying prices or plot sizes, lack thousand separators on the frontend. To enhance the readability of these values and therefore a better experience using the propery search and other forms for my customers, I require the implementation of thousands separators in the frontend display. However, it's crucial that the transmitted XML-file retains values wthou separators to ensure seamless handling on onOffice enterprise.

Numeric values, particularly those related to financial aspects such as buying price or property size, play a significant role in conveying information to potential customers. The current absence of thousand separators in the frontend display makes it challenging for customers to quickly comprehend, compare, input and search these values.

### Tasks

- [ ] Modify the onOffice for WP-Websites Plugin to include thousands separators in the frontend display for numeric form inputs, such as prices or plot sizes etc.
- [x] Implement a dynamic system that intelligently determines the appropriate thousands separator based on the numerical value's magnitude.
- [x] Provide customization options in the plugin settings that allow users to choose the style and format of thousand separators based on regional preferences / language. E.g. German and English are different.
- [x] Ensure that the values transmitted in the XML-file to onOffice enterprise do not include thousand separators, preserving the compatibility of the data.

E.g. German buying price: 1.000 or 10.000 or 1.000.000 instead of 1000 or 10000 or 1000000.

By implementing thousand separators in the frontend display, the onOffice for WP-Websites Plugin can significantly enhance the readability of numeric values for real estate agents and their customers, providing a more user-friendly and informative experience.

Example JavaScript:
- http://autonumeric.org/
- https://imask.js.org/

**Comment by dai-eastgate** [comment]
@fredericalpers: After investigating: 
This is the solution I plan to implement:
**In Backend:**
UI in onoffice-settings menu : 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/dff0eeb0-61a0-4c5e-9d18-b248140cb39c)

=> Do you agree with this UI?

**In Frontend:**
I will implement this for the following positions:
+ When the user enters value this field in form inputs (Estate List, Contact Form, Interest Form, Owner Form, Aplicant Search Form)

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/e02b86f0-dba9-4b51-a0a8-a877a32f97f9

1. **For "price fields"** (Ex: purchase price, lease,....)
My solution works fine.

2. **For others fields which is "numeric form inputs"** (property size(ex Living area,..))
Feasibility: some fields will need to be implemented but some fields should not be applied.
Because:
There are fields that when searched on the frontend enter values as "numeric form inputs", but their display format does not apply "a thousand separators".

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/6f2b2b88-c246-4599-af86-c6cc301f1b43

ex:  Correct Format: Latitude: 48.19691
       Wrong Format: Latitude: 4.819.691

=> We cannot use the only condition "type = number" will apply "thousand separators".

=> Please, provide the "exact list fields" Which has "numeric form inputs" that need to be applied "thousand separators". 

Purpose: to avoid applying "thousand separators" to unnecessary fields when applying "thousand separators" simultaneously for all "numeric form inputs" fields.

**Comment by dai-eastgate** [comment]
@fredericalpers Please take a look at my above comment (https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/721#issuecomment-1931596462) and let me know your opinions. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate you are right, we can not use this for every numeric field. 😅

Please implement this for all price and area/size related fields, e.g. buying price (kaufpreis) or living area (wohnflaeche).

**Comment by dai-eastgate** [comment]
@fredericalpers 

> Please implement this for all price and area/size related fields, e.g. buying price (kaufpreis) or living area (wohnflaeche).

Yes. I will need more time to list the fields related to price and area/size for you to confirm.



> Where are the differents between German, German (austria) and Italian? Please only implement a selection if there is an actual difference. We would prefer not to mention the countries and just showcase the difference in the numbers.

OK. I got it.

**Comment by dai-eastgate** [comment]
@fredericalpers 
> Yes. I will need more time to list the fields related to price and area/size for you to confirm.

This is all fields which I will apply "thousand separators"  feature:
- Price:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/414b122d-3dd9-4bd6-b1bf-75cf7bc420bd)
- Area:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8958dff9-a57f-4a86-949c-1b7693d95fb3)
Please confirm the list of fields above. Or do you want to add other fields?


> We would prefer not to mention the countries and just showcase the difference in the numbers.

I will implement UI in the office settings as image below. 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/65b5c9ee-22d0-4f46-bd16-b6b341355c16)
Do you agree with this UI?

**Comment by fredericalpers** [comment]
@dai-eastgate we would like you to remove the option for "Space (ex. 123 456,78)" and "No space". The current no space option should be the standard option. Only if chosen "Dot" and "Comma" should be used.

Please go ahead and implement it for the input fields related to price and area as mentioned in the list.

**Comment by dai-eastgate** [comment]
> @dai-eastgate we would like you to remove the option for "Space (ex. 123 456,78)" and "No space". The current no space option should be the standard option. Only if chosen "Dot" and "Comma" should be used.
> 
> Please go ahead and implement it for the input fields related to price and area as mentioned in the list.

Ok, I got it.Thanks!

**Comment by dai-eastgate** [comment]
I have implemented "thousand separators" feature in the Estate List, All Forms (owner form, interest form, applicant search form...)
This demo video: https://files.fm/u/h4ub2p9b3h 

**Note:** 
During testing, I found an issue:
On branch master, we cannot submit a decimal number (ex: 123,456.32) in the "Search Form" feature in Estate List: https://files.fm/u/fkjfub52n4

=> I only implement the "Thousands Separator" feature and can not implement the "Decimal Separator" feature
