### ISSUE TITLE
WP Script Dequeue function

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#737]
# Initiative
Enhance script management in the onOffice for WP-Websites plugin.

### Epic
Implement advanced script dequeuing action

### User story
The recent update to onOffice plugin version 4.15 has introduced challenges related to script management, particularly with regards to dequeuing and deregistering scripts.

https://developer.wordpress.org/reference/functions/wp_dequeue_script/
https://developer.wordpress.org/reference/functions/wp_dequeue_style/

Despite attempting to dequeue scrips in the functions.php file, the changes are ineffective as the scripts are loaded after the deqeues are executed. To address this issue, I require the implementation of a new action that allows me to continue dequeueing scripts. Additionaly, the priority of dequeues should be adjusted.

### Tasks

- [x] Develop and integrate a new action that enables script dequeuing
- [x] Adjust the priority of dequeues
- [x] Conduct thorough testing to ensure the effectivness and reliability of the new action

The implementation will address the script management issues faced by users after updating to onOffice plugin version 4.15. By providing a new action for script dequeuing, along with an adjusted priority, users will have enhanced control over script loading and management, leading to improved websites performance and functionality.

**Comment by dai-eastgate** [comment]
@fredericalpers Yes, I know this problem:
In version 4.15 we have implemented "Only load required scripts and CSS" #610
we use "wp_register_script" and "wp_enqueue_script" in namefile.php specifically in the "root-plugin/plugin" folder.
=> Despite your attempting to dequeue scrips in the functions.php file,
the changes are ineffective as the scripts are loaded after the dequeues are executed.

But if I implement "Develop and integrate a new action that enables script dequeuing" feature, I am afraid it will be difficult for us to ensure "Only load required scripts and CSS"
I need one more day to try implementing it, and then will accurately inform you about the feasibility of this task or the most optimal solution.

**Comment by dai-eastgate** [comment]
@fredericalpers 
We have found the only and most optimal solution to ensure:
+ "Develop and integrate a new action that enables script dequeuing"
+ "Only load required scripts and CSS"
This is my solutions:
Use "shortcode embedded" in page content (ex:[oo_estate view="Estate List"]) to detect page type (estate list, detail, forms, unit list,..)
=> can only load required scripts for that page.

We tried to implement it at this branch https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/wp-script-dequeue-function you can test it and review the code.

This is a video demo:

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/9a6ca0cb-d8af-415f-8a32-0b893728ec65

Please watch the video and let me know your opinions. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate it seems to be working fine this way. We will review it asap, thank you :)
