### ISSUE TITLE
Automated selection of renamed custom templates

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#749]
# Initiative
Enhance the usability of the onOffice for WP-Websites plugin

### Epic
Implement automated custom template selection

### User Story
As a real estate agent utilizing the onOffice for WP-Websites plugin, I encounter inefficiencies when creating e.g. new property lists. Currently, if I have customized the template for displaying property lists and renamed it from the default name, subsequent property lists do not automatically select the custom template. Instead, the plugin defaults to the provided default template, leading to manual selection and potential errors.

The current workflow for selecting templates for property lists lacks automation and introduces unncessary manual steps. This results in inconsistency and potential errors, especially when managing multiple property lists with custom templates. To address this issue and streamline the template selection process, I propose enhancing the plugin to automatically choose the correct custom template wheneber a new property list is created.

https://developer.wordpress.org/themes/template-files-section/page-template-files/

### Tasks

- [ ] Investigate the current mechanism for template selection in the onOffice for WP-Websites plugin
- [ ] Determine the feasibility of utilizing WordPress's page templates file functionality to ensure the automatic selection of custom templates
- [ ] Develop a solution to automatically detect and select custom templates based on their unique identifiers, even if renamed from the default name
- [ ] Implement a logic within the plugin to prioritize custom templates over default templates when creating a new property list
- [ ] Conduct thorough testing to verify the functionality and reliability of the automatic template selection

By implementing automatic selection of custom templates for property lists, the onOffice for WP-Websites plugin can significantly enhance user experience and streamline workflow for web agencies and real estate agents managing property listings on a website.

**Comment by yeneastgate** [comment]
@fredericalpers This is my investment result:
"As a real estate agent utilizing the onOffice for WP-Websites plugin, I encounter inefficiencies when creating e.g. new property lists. Currently, if I have customized the template for displaying property lists and renamed it from the default name, then property lists do not automatically select the custom template. Instead, the plugin defaults to the provided default template, leading to manual selection and potential errors."

Your desired state means:
When creating e.g. a new property list, property details, or new forms, and in the template selection of the "Layout & Design" box, "select renamed custom templates" will be the priority, right?
e.g. I customized a template and renamed it "custom_template" from the "default" template in the "estate" folder of "template.dist".
=> Your desired state is that:
When creating e.g. new property lists, "custom_template" will be prioritized selection of renamed custom templates
![Screenshot 2024-03-18 154905](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/29a16fc0-b408-4115-9200-bb45b05396f0)
![Screenshot 2024-03-18 155106](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/90962703-9596-4f67-bb2f-312bcd43adc2)

I have tried implementing it in this branch: [45378-automated-selection-of-renamed-custom-templates](https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45378-automated-selection-of-renamed-custom-templates).
Note: users need to have write file permission.

**Comment by yeneastgate** [comment]
> As a real estate agent utilizing the onOffice for WP-Websites plugin, I encounter inefficiencies when creating e.g. new property lists. Currently, if I have customized the template for displaying property lists and renamed it from the default name, subsequent property lists do not automatically select the custom template. Instead, the plugin defaults to the provided default template, leading to manual selection and potential errors.

@fredericalpers 
Your desired state means:
When creating e.g. a new property list, property details, or new forms, and in the template selection of the "Layout & Design" box, "select renamed custom templates" will be the priority, right?
e.g. I customized a template and renamed it "custom_template" from the "default" template in the "estate" folder of "template.dist".
=> Your desired state is that:
When creating e.g. new property lists, "custom_template" will be prioritized selection of renamed custom templates
![Screenshot 2024-03-18 154905](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/29a16fc0-b408-4115-9200-bb45b05396f0)
![Screenshot 2024-03-18 155106](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/90962703-9596-4f67-bb2f-312bcd43adc2)

**Comment by yeneastgate** [comment]
@fredericalpers This is my investigate result:

> As a real estate agent utilizing the onOffice for WP-Websites plugin, I encounter inefficiencies when creating e.g. new property lists. Currently, if I have customized the template for displaying property lists and renamed it from the default name, subsequent property lists do not automatically select the custom template. Instead, the plugin defaults to the provided default template, leading to manual selection and potential errors.

Your desired state means:
When creating e.g. a new property list, property details, or new forms, and in the template selection of the "Layout & Design" box, "select renamed custom templates" will be the priority, right?
e.g. I customized a template and renamed it "custom_template" from the "default" template in the "estate" folder of "template.dist".
=> Your desired state is that:
When creating e.g. new property lists, "custom_template" will be prioritized selection of renamed custom templates

![Screenshot 2024-03-18 154905](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/29a16fc0-b408-4115-9200-bb45b05396f0)
![Screenshot 2024-03-18 155106](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/90962703-9596-4f67-bb2f-312bcd43adc2)

I have implement on the branch [45378-automated-selection-of-renamed-custom-templates](https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45378-automated-selection-of-renamed-custom-templates)

Note: User must have permission to write the file

**Comment by yeneastgate** [comment]
> * Investigate the current mechanism for template selection in the onOffice for WP-Websites plugin

@fredericalpers Here are the results of my investigation of "current mechanism for template selection in the onOffice":

1.1.Prioritize:
Template selection will be prioritized in folder order as follows:
onoffice-theme in the WordPress "themes" folder  => Plugin "onoffice-personalized"  => "templates.dist" of wp onoffice plugin
1.2.Mechanism of operation(Mechanism of Saving template selection to Database)
Step 1: Selected template(default.php) information will be saved in the config as a URL
For example: onoffice-theme/templates/estate/default.php.
Step 2: When Changing Template Name, Only the name of the template file is changed. URLs saved in the config are not updated accordingly.
ex: When user has behavior to add a listview estate and select template "defautl.php".
Selected template information(onoffice-theme/templates/estate/default.php) will be saved in the config of
=> Because when the user renames the template in the custom template folder(default.php => renameDefault.php)
=> The database cannot save the renamed template into the database

**Comment by fredericalpers** [comment]
> Your desired state is that: When creating e.g. new property lists, "custom_template" will be prioritized selection of renamed custom templates
> 
> ![Screenshot 2024-03-18 154905](https://private-user-images.githubusercontent.com/104892108/313629507-29a16fc0-b408-4115-9200-bb45b05396f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzExNTgsIm5iZiI6MTcxMDgzMDg1OCwicGF0aCI6Ii8xMDQ4OTIxMDgvMzEzNjI5NTA3LTI5YTE2ZmMwLWI0MDgtNDExNS05MjAwLWJiNDViMDUzOTZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTk0MDU4NDFhYzcxZTc4YzNlYTgyMzllZGFhYzZiMmE1ZGViODliNDU3NzJiY2Y1OTA0YmZhOTFlNzJmY2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8taoe-da-FCuMogTxlqp4_1xhAvNeW6AfI2vO4fHuYw) ![Screenshot 2024-03-18 155106](https://private-user-images.githubusercontent.com/104892108/313629546-90962703-9596-4f67-bb2f-312bcd43adc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzExNTgsIm5iZiI6MTcxMDgzMDg1OCwicGF0aCI6Ii8xMDQ4OTIxMDgvMzEzNjI5NTQ2LTkwOTYyNzAzLTk1OTYtNGY2Ny1iYjJmLTMxMmJjZDQzYWRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTVkZDQ0NmJmMTgyNzcxMGEyMGUwNDEyMTgwMzg2ZjYxMzI4OThlMjNjZDAzYTY5ZjhiMzFiODYzOWM5MjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vFjtAB1kAsRmHvRaft-EDPVNh5d6ry68I7zjiVaa3ec)

that's correct :)

**Comment by yeneastgate** [comment]
Currently, we have found a solution based on using the "Creating Custom Page Templates for Global Use" mechanism.
To create a global template, we need to write an opening PHP comment at the top of the file that states the template’s name.
![Screenshot 2024-03-19 162133](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/948c7d41-d2c8-437e-9daa-28b81148f828)
However, the considerations of utilizing WordPress's page templates file functionality to automatic selection of custom templates must ensure the following conditions:
the directories must have permission to write data(put contents) to the file:
1.onoffice-theme/templates
2.onoffice-personalized/templates
![Screenshot 2024-03-19 162333](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/e3b572e7-a083-41a3-8f67-3e7f9a7bf8f9)

Because we use "file_put_contents" method to automatically write an opening PHP comment at the top of the file.
This is a demo video: https://files.fm/u/8pu5n3fysk#/view/3uud7nhban
You can review the code and test it in this branch: https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45378-automated-selection-of-renamed-custom-templates

**Comment by yeneastgate** [comment]
@fredericalpers Currently, we have found a solution based on using the "Creating Custom Page Templates for Global Use" mechanism.
To create a global template, we need to write an opening PHP comment at the top of the file that states the template’s name.
![Screenshot 2024-03-19 162133](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/fe08e7a4-bad5-4c55-b7d8-d4c7764dc1e4)
However, the considerations of utilizing WordPress's page templates file functionality to automatic selection of custom templates must ensure the following conditions:
the directories must have permission to write data(put contents) to the file:
1.onoffice-theme/templates
2.onoffice-personalized/templates
![Screenshot 2024-03-19 162333](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/7775eb29-5b22-4a5b-8a47-1d94fb018d5c)
Because we use "file_put_contents" method to automatically write an opening PHP comment at the top of the file.
This is a demo video: https://files.fm/u/8pu5n3fysk#/view/3uud7nhban
You can review the code and test it in this branch: https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45378-automated-selection-of-renamed-custom-templates

**Comment by fredericalpers** [comment]
@yeneastgate this seems to be working as we intended, thank you :)

**Comment by yeneastgate** [comment]
> the directories must have permission to write data(put contents) to the file:
> 1.onoffice-theme/templates
> 2.onoffice-personalized/templates

This is drawback of this solution.
=> I will continue to research to find a better solution can overcome this drawback and respond to you as soon as I find it.

**Comment by yeneastgate** [comment]
@fredericalpers 
1. According to the recommendation of WordPress Developer Resources (https://developer.wordpress.org/advanced-administration/server/file-permissions/#shared-hosting-with-suexec), the correct permissions is all directories should be 755 or 750.

2. For our solution, permissions are required for more "user:group" is "www-data" in addition to directory permissions is 755 with 2 directories :
+"onoffice-theme" directory (wp-content/themes/{your theme}/onoffice-theme/templates)
+ "onoffice-personalized" directory (/wp-content/plugins/onoffice-personalized/templates)

3. As my knowledge:
If the "/wp-content/themes" and "/wp-content/plugins" directories are owned by root or any other users other than www-data, you may not be able to install plugins, add themes, or even upload files to your website from the dashboard backend WordPress.

An issue you may face is automatically installing plugins, and themes in the WordPress admin will require you to log in via FTP/SFTP if the files aren't owned by www-data.

=> So this solution "feasibility of utilizing WordPress's page templates file functionality" can be implemented with condition "/wp-content/themes" and "/wp-content /plugins" directories which have "user:group" is "www-data".

4. For cases "/wp-content/themes" and "/wp-content /plugins" directories which do not have "user:group" is "www-data" permission.
We tried manually adding template files by editing the file locally and using FTP to upload the file to the server in this branch( [45378-automated-selection-of-renamed-custom-templates-v2](https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45378-automated-selection-of-renamed-custom-templates-v2))
This is the demo video, please watch and give me your opinion: https://files.fm/u/w65kq3aaxw#/view/w9jyr5kk8x
=> However, with this solution, we can not handle the behavior rename file of users to "automated selection of renamed custom template".
We only can display the Template Name of "WordPress's page templates file" when selecting the template in the backend.

There is my analysis of the feasibility of this feature. So that you have a clear overview and hope to help you decide the plan for this issue.

**Comment by fredericalpers** [comment]
Due to the priority and relevance of other issues and projects, this issue will be postponed to v5.3
