### ISSUE TITLE
Multiple mail recipients per form

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#752]
# Initiative
Improve the onOffice for WP-Websites Plugin Forms

### Epic
Multiple recipients for onOffice Forms in WordPress

### User story
As a real estate agent utilizing the onOffice for WP-Websites Plugin, I face limitations in the current form setup, restricting me to a single recipient for form submissions. Recognizing the need for efficient communication within my team, I seek the capability to add multiple recipients to onOffice forms.

The existing functionality of the onOffice for WP-Websites Plugin allows for the creation of forms that capture valuable leads and inquiries. However, the restriciton to a single recipient poses challenges, particulalry in team-based real estate operations. To enhance the flexibility of forms, I propose the implementation of a feature allowing multiple recipients for onOffice forms.

### Tasks

- [ ] Modify the form interface to incorporate a section for adding multiple recipients (CC recipients)
- [ ] Integrate the multiple recipient functionality that enables me to easily add, remove or modify recipients into the form settings backend (select2 dynamic option creation https://select2.org/tagging ?)
- [ ] Integrate a note that this feature will not work with contact forms on property detail pages.

By introducing the ability to specify multiple recipients for onOffice forms, the onOffice for WP-Websites Plugin can better accommodate the collaborative nature of real estate teams. This enhancement ensures that form submissions are efficiently directed to the appropropriate recipients within a real estate operation.

The design is just a general reference. It should be according to other multiselects as implemented before.

![mtpl-recipients](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/6e3a1f18-574c-44ba-a275-c8c55a9c89fa)

**Comment by dai-eastgate** [comment]
@fredericalpers Currently, I only see that the "cc" parameter is supported for the "Send Email" API on onOffice API.
https://apidoc.onoffice.de/actions/aktionen-ausfuehren/email-versenden/
For the "contact address" API which we are using to send emails in the current source code, we see that the "cc" parameter does not support this API. Watch the test video below:

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/e1c0f00c-0fc0-4ddc-84c2-d020a40bb02b


Please check with your IT department. Then respond for me.
What is the "parameter name" Which supports CC recipients of the "contact address" API?

**Comment by dai-eastgate** [comment]
@fredericalpers 
> ### Tasks
> * [ ]  Modify the form interface to incorporate a section for adding multiple recipients (CC recipients)
> * [ ]  Integrate the multiple recipient functionality that enables me to easily add, remove or modify recipients into the form settings backend (select2 dynamic option creation https://select2.org/tagging ?)
> * [ ]  Integrate a note that this feature will not work with contact forms on property detail pages.

 I have implemented it. Currently, the API does not have a parameter to be able to send cc recipients. I will complete this feature as soon as the API provides parameters to support sending cc recipients.
This is branch: 45790-multiple-mail-recipients-per-form. Please check it and watch the demo video https://files.fm/u/7jryy5qa2m#/view/xs47uyujsa
