### ISSUE TITLE
onOffice menu item disappears in the WP backend

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#769]
# Initiative
Bug fixing for the onOffice for WP-Websites Plugin

### Epic
Restore visibility of "onOffice" Menu Item in WordPress Admin Sidebar.

### User Story
As a user managing my website, I've encountered a bug where the "onOffice" menu item disappears from the left menu bar editing pages. This issue has arisen after updating to version 4.18 of the onOffice for WP-Websites plugin and is in direct correlation with [Commit 43305 backend performance](https://github.com/onOffice-Web-Org/oo-wp-plugin/commit/e4cd0fe5c2bc3164d66acfba5c91f547e98b3475). The disappearance of the "onOffice" menu item disrupts my workflow and makes it challenging to access important functionalities provided by the plugin.

To ensure seamless usability and functionality of the onOffice WordPress integration, I propose resolving the bug.

### Tasks

- [x] Investigate the changes introduced in version 4.18 of the onOffice plugin to identify the cause of the "onOffice" menu item disappearing.
- [x] Develop a fix to restore the visibility of the "onOffice" menu item in the WordPress admin sidebar when editing pages.
- [x] Conduct thoroug testing to verify that the bug fix resolves the issue effectively.

By addressing this bug, users will regain access to the "onOffice" menu item in the WordPress admin sidebar, allowing them to efficiently manage their website's functionalities without disruption.

Menu item: https://snipboard.io/dGBkru.jpg
Menu item dissapeared:  https://snipboard.io/bxKehR.jpg

**Comment by dai-eastgate** [comment]
@fredericalpers yes, I will check it now.

**Comment by yeneastgate** [comment]
@fredericalpers We have checked and found that the cause of this bug was that we were still using some plugin features on the edit page. However, we returned $pDI before those functions were executed.

We also did not expect this problem because coincidentally when using the editing page, we used the full-screen editing feature.

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/fd72747c-7e0f-486c-9aae-99218748c414)
We did not detect this bug during testing. We apologize for this problem.


Here is the list of plugin features used in the edit page
1. Menu at the office
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/abc63054-166f-4b8d-a4ba-d1b6c1344db0)
2. Bar menu at the office
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/78e24d9c-38e5-4f2d-b991-3a082d2d080c)
3. Cache in onoffice bar menu
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/ed50c730-fef4-465b-a021-955048d4d2fa)

4. Save page (add shortcode)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/97e323ef-c931-41a7-a46b-9db78004b6b1)

5. Delete page (remove shortcode)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/244e8b0e-efdb-42ac-98a8-cae328687364)

We've narrowed the impact down to just edit_page in the condition code.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/b0a74803-b056-48d3-ba54-111c2154e349)

Therefore other feature pages will not be affected. so the functionality of wp-onoffice-plugin on the client site is not affected

We have refactored the code. You can review and test it in this branch [45733-onoffice-menu-item-disappears-in-the-wp-backend](https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/45733-onoffice-menu-item-disappears-in-the-wp-backend).
Please watch the demo video and let me know your idea.
https://files.fm/u/tx36erpaay#/view/3zx4ywvr6e.
