### ISSUE TITLE
Implementation of energy certificate with a scale

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#825]
# Implementation of energy certificate with a scale

### Introduction
The current presentation of energy performance certificate data on property websites is not particularly appealing or user-friendly, as it is only displayed in text/table form. In order to improve the user experience and better address potential customers, a standard graphical display for energy performance certificates is to be implemented.

### User Story
As a real estate agent, I would like to have a more attractive presentation of the energy certificate data on my website. Currently, this data is only displayed as simple text/table, which is not very appealing. To improve the presentation, I would like to use a graphical representation for energy performance certificates. This will allow potential customers to see the energy efficiency of the property at a glance and process the information more easily. This visual representation will help to increase the attractiveness and professionalism of my website and increase the interest of potential customers.

### Task & Requirements
- [x] Development of the display and integration of the energy certificate data
- [x] Selection option for activating the display in the plugin backend
- [x] Carrying out tests to ensure that the graphical representation is displayed correctly on all device sizes, browsers etc. and accurately reflects the energy efficiency of the properties.

### Design / Screenshots

**Certificate of consumption:**
![energieausweis PNG (3)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/640f63ce-e6d7-4416-8410-49540f6fa8ea)

**Demand certificate:**
![energieausweis2 PNG (3)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/9c477959-ad70-41be-b9fc-5f7abaae3d1e)

**Comment by yeneastgate** [comment]
@fredericalpers After investigating the requirements, please confirm the following issues for us:
1. Is the Certificate of Consumption (Bedarfsausweis) energy certificate displayed like this image correct?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/ce4d3442-7099-4775-9642-499b4c16ed0e)

2. Is the Demand certificate(Verbrauchsausweis) energy certificate displayed like this image?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/4eb374ff-8810-416d-b31a-50829685a7a4)

3. Currently on the onOffice system we see 2 types of energy certificates: Industrial requirement-oriented certificate (Bedarfsausweis Gewerbe) and Industrial energy consumption certificate (Verbrauchsausweis Gewerbe)

=> So do we need to implement them?
=> If you need to implement them, please provide us with the images of the UI scale.

**Comment by yeneastgate** [comment]
@fredericalpers Please confirm it for me so I can continue with the implementation. Thanks

**Comment by fredericalpers** [comment]
@yeneastgate the energycertificates for industrial (Gewerbe) will be implemented later, I will have to do some more research on these first.

The UI for the current implementation looks good so far. However I have a few minor adjustments.

- [ ] Appropriate gap between headline, scale and table. Recommendation for the scale. top margin: 1.5rem, bottom margin: 2rem or even 2.5rem.
- [ ] Use a more saturated green, as the light green can be hard to see on different screens.

**Comment by yeneastgate** [comment]
> @yeneastgate the energycertificates for industrial (Gewerbe) will be implemented later, I will have to do some more research on these first.
> 
> The UI for the current implementation looks good so far. However I have a few minor adjustments.
> 
> * [ ]  Appropriate gap between headline, scale and table. Recommendation for the scale. top margin: 1.5rem, bottom margin: 2rem or even 2.5rem.
> * [ ]  Use a more saturated green, as the light green can be hard to see on different screens.

@fredericalpers I got it. Thanks!

**Comment by yeneastgate** [comment]
@fredericalpers I have implemented it and this is demo video: 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/a6ac934d-a324-4729-8be5-b18bffdec389

Please check and let me know your opinion. Thanks!
