### ISSUE TITLE
Displaying multiple property lists and OSM on one page - Fix after leaflet.js update

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#847]
# Displaying multiple property lists and OSM on one page - Fix after leaflet.js update

### Introduction
As mentioned in Issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/703#issuecomment-1907305962 there is still an issue that needs to be addressed.

### User Story
As a user of the onOffice WordPress plugin, I want each property list and OSM map on a single page to display the correct properties and maps, so that all information is correctly and clearly presented.

Following the release of the Improve Pagination https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/695 update, an issue has arisen when multiple property lists and OSM maps are used on the same page. The current state results in an error and no OSM for the second property list. Thus, an additional fix is necessary to ensure that each property list matches the correct OSM map and displays the correct properties.

<details><summary>Error or also see browser console</summary>
<p>

Uncaught Error: Map container is already initialized.
    at e._initContainer (Map.js:1094:10)
    at e.initialize (Map.js:136:8)
    at new e (Class.js:24:20)
    at t.map (Map.js:1750:9)
    at immobilienliste-alle-immobilien/:539:21
    at immobilienliste-alle-immobilien/:557:7

</p>
</details> 

### Task / Requirements

- [x] Fix the bug mentioned in https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/703#issuecomment-1907305962
- [x] Each property list must display a map (if activated and one of the propertys address is shared)
- [x] Each  map must show the correct locations of properties that are displayed in the corresponding list.
- [x] Ensure that each OSM map displays only the locations of the properties in the corresponding list.
- [x] Regression tests to ensure that previous functionalities are not affected.

**Comment by yeneastgate** [comment]
@fredericalpers  I have fixed this bug. Please check the link video evidence below:
- For single property list: https://files.fm/u/yku75ynzp7#/view/n5njun8nn7
- For Multiple property lists:  https://files.fm/u/kzv7j7x6p4#/view/kgj2d7ajt4

**Note:**
1. Only new users can use this feature. For old users, please copy the template.dist folder to use this feature.
2. I also encounter the same bug when using Google Maps
Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate Seems to be working for mutliple lists and OSM now, thank you :)

> I also encounter the same bug when using Google Maps
Please check and let me know your opinion. Thanks!

please go ahead and fix this for Google Maps as well

**Comment by yeneastgate** [comment]
@fredericalpers I have fixed the bug using multiple property lists and Google Maps. Here is video evidence:
- Multiple property list: https://files.fm/u/38wky452hr#/view/68f45sf3qv
- Single property list: https://files.fm/u/y2q3khqpr4#/view/73uwkc5n3s

Please check and let me know your opinion.

**Comment by fredericalpers** [comment]
@yeneastgate thank you, we will review this as soon as possible :)

**Comment by fredericalpers** [comment]
Vorgezogen auf 5.2
