### ISSUE TITLE
Extending Pagination Features for Theme Compatibility

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#850]
# Extending Pagination Features for Theme Compatibility

### User Story
As a user of the onOffice WordPress plugin, I want the pagination feature to be compatible with WordPress themes' pagination, so that I can use my preferred theme's pagination style seamlessly.

In the release of version 4.20, the pagination improvements (#695) were introduced, but they currently work only with the pagination system of the onOffice for WP-Websites plugin. In version 4.21, an extra HTML `<div>` (#849) will be removed, and further enhancements are needed to ensure that the pagination feature can also be used with WordPress themes' built-in pagination systems.

With these enhancements, users of the onOffice WordPress plugin will be able to utilize their preferred WordPress theme's pagination system seamlessly, enhancing the overall integration and user experience.

### Task / Requirements

- [ ] The pagination feature must be compatible with the default pagination styles and systems provided by WordPress themes. 
![wptheme-pag](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/308f605a-7a96-4e90-9849-3fb93d952b24)

- [ ] Ensure that the pagination works correctly across different themes.
- [ ] Ensure that users who prefer the plugin's pagination system can continue to use it without any issues.

**Comment by dai-eastgate** [comment]
@fredericalpers 
1. The reason the pagination function does not work with multi-shortcode is that:
In the template file code, we have not added the pagination code if the user chooses the "Pagination By WP Theme" option
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f8d5b502-9746-414b-a422-08457a27e515)

=> So currently the pagination function is showing using the "wp_link_pages" function in the content.php file of the WordPress theme which is active
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/42976919-e57a-481d-81a5-6ab295b9d9cc)

2. However, each different WordPress theme uses the "wp_link_pages" function in the content.php file differently.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/dcc1a3d9-82aa-48e3-8fd7-395a2824293a)

=> We cannot fulfill this requirement "The pagination feature must be compatible with the default pagination styles and systems provided by WordPress themes."
=> We only add pagination features with common formats (compatible with default pagination styles) for WordPress themes as follows
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/45c579bc-cc8b-4898-b129-8b0282cd505c)

You can see the following demo: https://files.fm/f/38tqv6y2g6
