### ISSUE TITLE
Fix Shortcode Recognition for Detail Pages in WP Bakery Builder

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#852]
# Fix Shortcode Recognition for Detail Pages in WP Bakery Builder

### User Story
As a user of the onOffice WordPress plugin, I want the shortcode for detail pages to be recognized correctly when using the "Raw HTML" or "Code" elements in WP Bakery Builder, so that I can utilize these elements without issues.

Customers have reported that the shortcode for detail pages is not recognized when using the "Raw HTML" or "Code" elements in WP Bakery Builder. However, the shortcode works correctly when using the normal text element. This bug needs to be investigated and fixed to ensure that the shortcode functions properly regardless of the WP Bakery element used.

By addressing this bug, users will be able to utilize the detail page shortcode within any WP Bakery Builder element, improving the flexibility and usability of the onOffice WordPress plugin.

### Tasks / Requirements

- [ ] The shortcode for detail pages should be recognized and rendered correctly when placed inside the "Raw HTML" element in WP Bakery Builder.
- [ ] The shortcode for detail pages should be recognized and rendered correctly when placed inside the "Code" element in WP Bakery Builder.
- [ ] Ensure that the shortcode functionality is consistent across different WP Bakery elements, including "Raw HTML," "Code," and normal text elements.

**Comment by yeneastgate** [comment]
@fredericalpers After investigate, I found that saving the content of the detail page does not work because the post content of <code>Raw HTML</code> is being encoded, which prevents adding Dynamic Rewrite Rules and causes the detail page to not display.
![image](https://github.com/user-attachments/assets/23af1a8d-205a-4685-9eae-7892635408a1)

> * The shortcode for detail pages should be recognized and rendered correctly when placed inside the "Code" element in WP Bakery Builder.

![image](https://github.com/user-attachments/assets/37b10b91-8c7f-42a6-8fcc-ab033a524fe7)

Currently, I see that only <code>Raw HTML</code> and <code>Raw JS</code> are being encoded when saved. Can you clarify which <code>Code element</code> you are referring to?

**Comment by fredericalpers** [comment]
@yeneastgate I think the <code>Code element</code> might have been a custom element. I can not find it anymore. You can ignore this.

**Comment by yeneastgate** [comment]
@fredericalpers I got it, thank you

**Comment by yeneastgate** [comment]
@fredericalpers I have implemented and here is video evidence: 

https://github.com/user-attachments/assets/b1d4a6cd-3bb3-425f-aea1-94de182f14ea

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate thank you, we will review this as soon as possible :)
