### ISSUE TITLE
Implementation of address completion form for property website.

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#853]
# Implementation of address completion form for property website.

### Introduction
Address completion can currently only be done from onOffice enterprise via e-mail. 

### Userstory
As a property agent, I would like to have a customizable address completion form on my website that is linked to the onOffice enterprise system and can be easily managed via the onOffice for WP-Websites plugin. So that customers who initially contact me via the website can conveniently provide the additional information required, making it easier for me to collect necessary data and improve communication.

By implementing this feature, the property agent can streamline the process of collecting additional client information, improve the efficiency of client interactions and enhance the overall website experience.

Further Information: 

- [API Doc Address completion](https://apidoc.onoffice.de/actions/informationen-abfragen/adressvervollstaendigungsfelder/)
- [Current Address Completion enterprise](https://de.enterprisehilfe.onoffice.com/help_entries/address-completion/?lang=en)

### Task / Requirements

- [ ] Development of a new form template of the type "addresses" in the onOffice for WP-Websites plugin.
- [ ] Integration of the onOffice API for dynamic retrieval of address completion fields. All fields that are released for address completion should be displayed in the field lists with the respective categories, as with the other forms.
- [ ] Extension of the onOffice for WP-Websites plugin for easy customization of the "addresses" form template.
- [ ] Ensure that the form fields are filled based on the address completion fields of the onOffice API.
- [ ] The front-end design is based on the existing forms.

### Design / Screenshots
**Backend List:**
![plugin-backend1](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/2ec7404e-f39c-4a93-a523-c19b53eb4bdd)

**Backend Form:**
![Plugin-backend2](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/daf75634-93d5-462b-8266-b226e7cef271)

**Comment by yeneastgate** [comment]
@fredericalpers After investigating, do you want to do the following steps?
Step 1: I have created a contact form in the backend with a list of fields from the address completion API.
![image](https://github.com/user-attachments/assets/96a300a6-8527-47f3-ac68-f26b2f670597)

Step 2: On the front-end, I have displayed the form interface as follows:
![image](https://github.com/user-attachments/assets/39e7300a-c049-4846-9139-d1e7c076e44a)

Step 3: After clicking the submit button:
We will call the API to create an address record in the enterprise system (at this step, we will obtain an address ID to use for sending the email below).
I will use the [API to send an email](https://apidoc.onoffice.de/actions/aktionen-ausfuehren/adressvervollstaendigung-versenden/) and create an address completion email to the user.
![image](https://github.com/user-attachments/assets/2996a1d6-8661-4112-94d7-2b8277932482)

If my above statements are correct, we can start implementing these steps. Do you want to add or modify anything?

**Comment by fredericalpers** [comment]
@yeneastgate I will have to adjust the requirements one more time, sorry about that. I will update it as soon as possible.

**Comment by fredericalpers** [comment]
requires more preparation and will be implemented at a different time.
