### ISSUE TITLE
Fix Email sending and creating data records issue with Honeypot Function on Property Detail Pages

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#857]
# Fix Email sending and creating data records issue with Honeypot Function on Property Detail Pages

### User Story
Based on customer feedback, there have been issues with incoming emails from property detail pages when the honeypot function is enabled. The form indicates successful submission, but no emails are received, and no address records are created. This issue appears to have started with version 4.18.

### Task / Requirements

- [x] Analyze the code to identify what is causing the failure in email sending and creating data records when the honeypot function is active.
- [x] Ensure that when a form is submitted, the email is correctly sent to the specified address.
- [x] If applicable ensure that the address data record is properly created.
- [x] Ensure that the honeypot function works as intended, preventing spam without interfering with legitimate form submissions.

**Comment by yeneastgate** [comment]
@fredericalpers I have checked and currently the honeypot is not working on the detail page when using advanced custom fields. Is this the issue you are facing?

Please watch the bug video: [https://files.fm/f/uj545er3ry](https://files.fm/f/uj545er3ry)

If so, please confirm so I can proceed with the implementation.

**Comment by fredericalpers** [comment]
@yeneastgate It seems like this is the case. Please go ahead and proceed with the implementation.

**Comment by yeneastgate** [comment]
> @yeneastgate It seems like this is the case. We will investigate further.

@fredericalpers Yes, I will wait for your response.

**Comment by fredericalpers** [comment]
@yeneastgate unfortunately, this has not been confirmed. the error seems to persists even without acf.

however we would like to try your fix on a test website. Please create a Pull Request :)

**Comment by fredericalpers** [comment]
Our further tests have shown that:

- The honeypot field is not added to the form. Therefore no e-mails are received.
- The problem ONLY seems to exists if the units are to be displayed in the shortcode ([oo_estate units="Units list" view="detail"]). 
- It also does not seem to work if the shortcode with unit list is stored via the Gutenberg "Shortcode".

https://testinstanz-mr.onofficeweb.com/
Here the suggested fix also works for the unit list with the current detail page. As soon as a new detail page is created, the whole functionality with units no longer works. We suspect that the shortcode was stored somewhere outside ACFs/Gutenberg in the past, e.g. in the Classis Editor or in the database.

Related to Files are not loaded on property detail page unit Issue #799   ?

**Comment by fredericalpers** [comment]
Info: Nach #799 nochmal testen, ob noch weitere Änderungen notwendig sind, oder ob 799 reicht.

**Comment by fredericalpers** [comment]
Should be fixed with the new release v5.0 and #800

**Comment by fredericalpers** [comment]
Durch https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/800 bereits behoben.
