### ISSUE TITLE
Critical error when using empty "Radius" for Similar Estates

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#859]
# Critical error when using empty "Radius" for Similar Estates

### User Story
Currently, the "Similar Estates" feature in the plugin encounters a critical error if the radius field is left empty. This limitation hinders users who do not wish to restrict their search based on a specific radius to their property. To enhance the usability and flexibility of the similar estates functionality, the system should allow users to leave the radius field blank without causing an error, similar to the "geo_positions" search feature.

<details><summary>debug.log</summary>
<p>

```
[10-Jul-2024 07:56:54 UTC] PHP Fatal error:  Uncaught TypeError: onOffice\WPlugin\DataView\DataViewSimilarEstates::setRadius(): Argument #1 ($radius) must be of type int, string given, called in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataSimilarEstatesSettingsHandler.php on line 125 and defined in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataViewSimilarEstates.php:137
Stack trace:
#0 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataSimilarEstatesSettingsHandler.php(125): onOffice\WPlugin\DataView\DataViewSimilarEstates->setRadius('')
#1 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataSimilarEstatesSettingsHandler.php(102): onOffice\WPlugin\DataView\DataSimilarEstatesSettingsHandler->configureDataSimilarEstatesSettings(Object(onOffice\WPlugin\DataView\DataViewSimilarEstates), Array)
#2 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Gui/AdminPageSimilarEstates.php(311): onOffice\WPlugin\DataView\DataSimilarEstatesSettingsHandler->createDataSimilarEstatesSettingsByValues(Array)
#3 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(324): onOffice\WPlugin\Gui\AdminPageSimilarEstates->save_form('')
#4 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-admin/admin-post.php(85): do_action('admin_post_onof...')
#7 {main}
  thrown in /www/htdocs/w01dbd85/testinstanz-fal.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/DataView/DataViewSimilarEstates.php on line 137
```

</p>
</details> 

### Task/ Requirements

- [x] Review the relevant sections of the codebase related to the "Similar Estates" functionality.
- [x] Ensure the backend logic is updated to handle cases where the radius is not provided.
- [x] Then the search results should include similar estates without considering the distance constraint.
- [x] Perform thorough testing to confirm that leaving the radius field empty does not impact other parts of the system negatively.

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented the fix for the empty "Radius" issue. Additionally, I noticed that the "Amount of Estates" field was encountering a similar error, and I have resolved that as well. Here is video evidence: 

https://files.fm/f/tbr7ubt5n7

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate thank you :) we will review this as soon as possible
