### ISSUE TITLE
Removing Pagination from the Detail Page Template

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#862]
# Removing Pagination from the Detail Page Template

### Introduction
In 2021, [pagination was revised](https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/68) and seems to have been unnecessarily implemented in the detail page template. Customers have often asked how to remove the pagination or complained about it. 

### User Story
As a real estate agent, I want the unnecessary pagination removed from the detail page template to provide a better user experience and increase customer satisfaction.

By removing the unnecessary pagination from the detail page template, we improve the user experience and this leads to higher customer satisfaction. Ultimately, this can result in more successful transactions and a better reputation for the real estate agents.

- https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/master/templates.dist/estate/default_detail.php#L435

### Tasks / Requirements

- [x] Review the code and structure for pagination.
- [x] Remove the all relevant code sections related to pagination on the detailpage.
- [x] Ensure all removed code sections are correctly and completely removed without leaving any remnants.
- [x] Test the detail page to ensure it displays correctly without pagination.
- [x] Ensure no other functions of the detail page are affected.

**Comment by yeneastgate** [comment]
@fredericalpers I have removed this pagination code in the detail template. Here is evidence. Please check and review it. Thanks!

https://github.com/user-attachments/assets/c0000e12-4a63-4bea-9c68-297f49bbf124

**Comment by fredericalpers** [comment]
@yeneastgate thank you, we will review this as soon as possible :)
