### ISSUE TITLE
Persistence of the property list with missing or same name

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#865]
# Persistence of the property list with missing or same name

### Introduction
If a new property list is created and an attempt is made to save it without a name or with a name that is the same as an existing list, all the settings made are deleted. The error “There was a problem saving the list. The Name field must not be empty.” is displayed.

### User Story
As a real estate agent, I want to make sure that all my changes to a new property listing are retained, even if I forget to give the listing a name, so that I don't lose any data and don't have to repeat my work unnecessarily.

This change ensures that users do not lose any data when creating real estate listings and can therefore work more efficiently.

### Task / Requirements

- [x] When trying to save the list, the error message should still be displayed, but there should no longer be an automatic page reload
- [x] Implementation of notifications for unsaved changes Feature
- [x] **If the name is empty:** The Name field must not be empty. Do you want to leave the page without saving? [Link]Leave without saving[/Link].
- [x] **If the name is the same:** Please make sure that no other view with this name exists, even if it has a different type. Do you want to leave the page without saving?  [Link]Leave without saving[/Link].

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented this issue. Here is evidence, please check it and let me know your opinion. Thanks!

https://github.com/user-attachments/assets/456cc65e-f78c-46ff-8b6b-2ba01cb5134a

**Comment by fredericalpers** [comment]
@dai-eastgate this seems to be working as intendet now, thank you! :) we will review this as soon as possible
