### ISSUE TITLE
Permanently Marked Required Fields and Correct Local Area Search in Applicant Forms

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#868]
# Permanently Marked Required Fields and Correct Local Area Search in Applicant Forms

### Introduction
In https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/641, we made the required field checkboxes permanently marked and non-deselectable. However, this seems to have only been implemented for the property list. For applicantform.php, the permanently marked required fields are missing and are not made non-deselectable. Additionally, in applicantsearchform.php, the radius search looks completely different and needs to be corrected.

### User Story
As a real estate agent, I want the required fields in the applicantform.php and applicantsearchform.php forms to be permanently marked and non-deselectable. Additionally, I want the local area search in applicantsearchform.php to be correctly displayed and functional so that users have a seamless and consistent experience.

By implementing this user story, we ensure that the usability and functionality of the applicant forms in the real estate portal are improved.

### Task / Requirements

Required Fields in applicantform.php:
- [x] All required fields are marked with checked and disabled attributes.Us
- [x] Users cannot deselect the marked required fields.

Local area search in applicantsearchform.php:
- [ ] The functionality should resemble the same as the other geoPosition
- [x] All required fields are marked with checked and disabled attributes.Us
- [x] Users cannot deselect the marked required fields.

![geoPosition-applicantsearch (1)](https://github.com/user-attachments/assets/2586b618-bbba-4e83-a014-85d78ce22969)
![geoPosition-interest-form (1)](https://github.com/user-attachments/assets/48777a3d-5b47-4dad-bf43-e79bdc138d5a)
![geoPosition-propertylist (1)](https://github.com/user-attachments/assets/d44bdf40-eb0d-45af-a048-ae44445e142b)

**Comment by dai-eastgate** [comment]
@fredericalpers After investigating this task, I need to confirm the following:
- In applicantsearchform: there are 4 fields 
![image](https://github.com/user-attachments/assets/ca830dec-d256-4e75-b4e9-80851e28a2ed)
- In applicantform: there are 5 fields
![image](https://github.com/user-attachments/assets/099bee91-f18a-43e8-985e-c0b7a3633d5b)

=> Which fields are required to be checked and disabled in two Forms(Interest Form, Application Search Form)?

- > Additionally, in applicantsearchform.php, the radius search looks completely different and needs to be corrected.

   Currently, the Applicant Search Form does not have a select radius section. Would you like to add select radius section to Admin Applicant Search Form?
 
![image](https://github.com/user-attachments/assets/acdefeee-3843-43ba-ad55-9f2a5c44e577)

**Comment by fredericalpers** [comment]
@dai-eastgate the fields (geoPosition) should be the same as in the property list. All 5 values, country, city, zip code, street and radius must be present. The mandatory fields should be the same as in the property list. Furthermore, the same info text must be visible.

**Comment by dai-eastgate** [comment]
@fredericalpers I checked and found that there is a restriction on the radius checkbox from being generated in the Application Search Form. Could you please confirm if you would like me to enable this feature in the Application Search Form? I want to make sure I understand your intent correctly before making any changes.
![image](https://github.com/user-attachments/assets/befe2047-c62f-4972-90d7-3f611fa2c1b3)

**Comment by fredericalpers** [comment]
> @fredericalpers I rechecked commit code and found that this commit [38014b6](https://github.com/onOffice-Web-Org/oo-wp-plugin/commit/38014b66fba18d371cce1e185b63563a2e8404e9) has already implemented radius suppression in the Applicant Search Form. Please take a look at this commit and let me know your opinion. Thank you!

@dai-eastgate please leave it as it is then, thank you for doing your due diligence! :)

**Comment by dai-eastgate** [comment]
@fredericalpers I got it, I will continue to implement this issue

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented it. Here is evidence. Please check and let me know your opinion. Thank you!

https://github.com/user-attachments/assets/00d8e63a-8dca-4447-a931-59730555068b
