### ISSUE TITLE
Improvement of labels for contact person data and individual labeling on the property details page

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#880]
# Improvement of labels for contact person data and individual labeling on the property details page

### Introduction
As a website owner, I would like labels to be displayed for the contact details on the property details page to increase user-friendliness and clarity for the visitor.

### User Story
The purpose of this user story is to ensure that customizable labels are displayed for the contact person data on the detail page of a property. These labels should make it easier for the website visitor to quickly recognize and assign the various information about the contact person. However, there are some specially assembled fields for which no labels should be displayed by default, unless a developer explicitly adds them by customizing the template.

This customization is intended to help improve the user experience on the property detail page by presenting important contact information in a clear and understandable way. At the same time, developers should be given the flexibility to implement special requirements through individual customizations.

### Task / Requirements

- [x] Labels should be output for all standard fields of the contact person data.
- [x] It should be possible to customize these labels.
- [x] Labels should not be output by default for specially composed fields, as in the code reference https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/master/templates.dist/estate/default_detail.php#L205
- [x] A label for these fields can only be added by individual customization of the template by a developer.
- [x] An interface is to be made available in the backend that the website owner can use to customize the labels for contact persons. See also property lists.
- [x] The presentation of the labels should be consistent and user-friendly to ensure a uniform appearance.
- [x] Labels should be easy to read on both desktop and mobile devices and adapted to the design of the website.

**Comment by dai-eastgate** [comment]
> * [ ]  Labels should not be output by default for specially composed fields, as in the code reference https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/master/templates.dist/estate/default_detail.php#L205
> * [ ]  A label for these fields can only be added by individual customization of the template by a developer.

@fredericalpers Does this mean that for the specially designated fields such as imageUrl, Anrede, Titel, Vorname, Name, Zusatz, Strasse, Plz, Ort, there will be no custom label feature available for these fields?
![image](https://github.com/user-attachments/assets/18773bda-98c2-4e05-b894-c70ce0631dd2)

**Comment by fredericalpers** [comment]
> > * [ ]   Labels should not be output by default for specially composed fields, as in the code reference https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/master/templates.dist/estate/default_detail.php#L205
> > * [ ]   A label for these fields can only be added by individual customization of the template by a developer.
> 
> @fredericalpers Does this mean that for the specially designated fields such as imageUrl, Anrede, Titel, Vorname, Name, Zusatz, Strasse, Plz, Ort, there will be no custom label feature available for these fields? ![image](https://private-user-images.githubusercontent.com/106214469/358554002-18773bda-98c2-4e05-b894-c70ce0631dd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTM4ODQsIm5iZiI6MTcyMzgxMzU4NCwicGF0aCI6Ii8xMDYyMTQ0NjkvMzU4NTU0MDAyLTE4NzczYmRhLTk4YzItNGUwNS1iODk0LWM3MGNlMDYzMWRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTQxNWE4ZDYxNjQwNmZlN2MzMzA2YTQ1OGU2Nzc1NjQwZDE2MWY2NjM1M2ZiNjZjZjNkY2UyOTU2MzQ1YmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2QUl54C1owM0SjQy-telGVeHz4wSwJIKSrclCzxf9K8)

@dai-eastgate correct! for those fields specially designated fields no custom label freature should be available

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented the label for contact person data. I have tested it in multiple browser such as: Google Chrome, Edge, Firefox, Opera and mobile devices. Here is video evidence 
- PC: https://files.fm/f/p9s879qgua
- Mobile: https://files.fm/f/7tcmsgybax

**Note:** This feature is related to backward compatibility. Users who want to use this feature must either copy the template or select the default_detail.php template file in the templates.dist folder.
Please check and let me know your opinion. Thank you!
