### ISSUE TITLE
Ownerform Customizable form creation with drag-and-drop function

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#899]
# Ownerform Customizable form creation with drag-and-drop function

### User Story
As an administrator in the backend, I would like to have the option to flexibly design the lead generator form (ownerleadgeneratorform.php) to display it as a modal or normal form and to determine the order of the fields per page using drag-and-drop to ensure an optimal user experience.

In https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/878 the form, which was previously only available as a modal, was adapted so that it can also be displayed as a regular multi-page form.
In this user story, several important functions are added to the existing lead generator form in the backend. In addition, users (administrators or customers) want to be able to customize the order of the form fields per page. This is done through an improved drag-and-drop system in the backend, which clearly visualizes both the placement of the fields within the form and the assignment to the respective pages (maximum 6 pages).

### Task / Requirements

- [x] In the backend, administrators can adjust the order of the fields in the form using an intuitive drag-and-drop function.
- [x] A function is implemented that allows users to assign fields to different pages of the form.
- [x] The maximum number of pages per form is set to 6.
- [x] Each field can be assigned to a specific page by drag-and-drop.
- [x] A validation ensures that no more than 6 pages are created.
- [x] The drag-and-drop system must be fluid and intuitive to use so that even inexperienced users can easily move the fields and assign them to pages.
- [x] The functionality must be usable on different screen sizes and browsers

**Comment by fredericalpers** [comment]
@dai-eastgate if possible display them in one block, but have lines and the headlines "page 1", "page 2" etc. separate them. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers 
I've created a UI for this feature. Please take a moment to watch my demo video and share your feedback. Thank you.
Note: I have currently set each page's title as "Page 1," "Page 2," etc. Do you have any suggestions for the titles?

https://github.com/user-attachments/assets/9bc9cbe9-3985-40d1-8e32-2e61eb0c5806

**Comment by fredericalpers** [comment]
@dai-eastgate Thank you for the changes so far, they look really good!

Just a small note: The "Add Page" button could look a bit more like a real button to make it clearer as such. Perhaps tweaking the style a bit would help.

Additionally, it would be great if the "Remove Page" button could be styled in red to better indicate that it's a delete action.

Thanks again for the great work so far!

**Comment by dai-eastgate** [comment]
@fredericalpers sorry, I checked again and need you to confirm the following issues:
1. The old data will be backed up and stored by default on page 1 when the new version is released.
2. When adding a new page using the "Add" button, it will be added to page 1. Users can then drag and drop it to other pages.
3. Should the page titles be displayed on the front-end, and should there be an option in the backend to change the page titles?
![image](https://github.com/user-attachments/assets/caf35e7c-8616-43f5-9bb6-3d20b13bdd43)

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
>The old data will be backed up and stored by default on page 1 when the new version is released.

👍👍👍

>When adding a new field using the "Add" button, it will be added to page 1. Users can then drag and drop it to other pages.

👍👍👍

>Should the page titles be displayed on the front-end, and should there be an option in the backend to change the page titles?

Yes the page titles should be displayed. Please go ahead and use a <span>-Tag for it. These should be exchangable in the template, so our customers can customize it to their wishes.

**Comment by fredericalpers** [comment]
>@fredericalpers Could you please explain what you mean by "-Tag" in this context?

The headline in the frontend should not be a < h2> or something. It should be a simple < span>. Github changed this into "-tag", sorry about that.

>As I understand it, you want customers to be able to customize the page titles in the template according to their wishes.

Please do not integrate the customization possiblity in the backend. Page titles should only be customizable in the template itself, with custom code. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers Please look at my demo video and let me know your opinions. Thanks!

https://github.com/user-attachments/assets/ab5ab785-ea25-4ab8-853f-182fb150f05e

https://github.com/user-attachments/assets/0eb00c41-ee02-483f-96fb-86e09db72ebc

**Comment by fredericalpers** [comment]
@dai-eastgate Thank you, we will review this as soon as possible :)
