### ISSUE TITLE
Integration of "City-Select" into the Location Field of the Address List Search

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#908]
# Integration of "City-Select" into the Location Field of the Address List Search

### User Story
Currently, the location field (fieldname: Ort) in the address list search of the onOffice for WP-Websites Plugin integration is represented as a simple text input, where users have to manually type in the desired location. To improve the user experience and reduce potential input errors, the text input should be converted into a dropdown menu ("City-Select"). This dropdown will display the available locations imported from onOffice enterprise, allowing users to select the desired location from the list instead of manually entering it.

This functionality has already been implemented for the location field in the property list (see Issue #655 and Pull Request #665) and should now also be applied to the location field in the address list search.

Users of the address list search should be able to use the location field more efficiently by selecting from a predefined list of locations, improving search speed and reducing potential input errors.

### Task / Requirements

- [ ] Add checkbox in the backend to enable display as a dropdown
- [ ] If enabled, the location field in the address list search should be presented as a dropdown menu instead of a text input. The checkbox should not be enabled by default to avoid problems with backwards compatibility.
- [ ] The dropdown should allow easy navigation and display all locations available in onOffice enterprise.

**Comment by fredericalpers** [comment]
@dai-eastgate @yeneastgate how long would this take to implement if you prioritize it?

**Comment by yeneastgate** [comment]
> @dai-eastgate @yeneastgate how long would this take to implement if you prioritize it?

We need one and a half day to implement this issue

**Comment by yeneastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thanks!


https://github.com/user-attachments/assets/63c86b8b-cc50-473a-94d8-84dcbd20698e

**Comment by fredericalpers** [comment]
@yeneastgate looks good to me! Only one minor adjustment needs to be made. The checkbox to enable the drodpown should be disabled as long as the field itself is not selected for "show in search". Thank you :)

**Comment by yeneastgate** [comment]
> @yeneastgate The checkbox to enable the drodpown should be disabled as long as the field itself is not selected for "show in search". Thank you :)

@fredericalpers I fixed it. Please help us to review this PR. Thanks! 


https://github.com/user-attachments/assets/308e5ed7-b0ba-43cf-a52a-6ea9196ff90a
