### ISSUE TITLE
Implementation of the “bildWebseite” field in adresses

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#914]
# Implementation of the “bildWebseite” field in adresses

### Introduction
For the address lists and address details page, we have the new system field “imageWebsite”. You can activate the field in the administration. 

Administration > Input fields > Module: Address management > Category: Administration 

### User Story
As a user, I would like to be able to choose between the pass photo and the “image website” field on the address list and address details page, so that I can display a corresponding high-resolution image for each address record. The functionality of the bildWebsite field should be implemented both in the address list and on the address details page. As is currently the case, there should be 2 checkboxes to choose from. If no image is selected, no image should be displayed. If both images are selected, the new field “bildWebsite” should take priority.

### Task Requirements

- [x] The system field “bildWebseite” is to be added to the address list.
- [x] The system field “bildWebseite” is to be added to the address detail page.
- [x] The user can choose between the pass photo and the image of the website (from “bildWebseite”).
- [x] The user photo should be replaced by the “bildWebseite” field.
- [x] The passport photo should be selected by default because the image website field is not active by default in onOffice enterprise.

**Comment by dai-eastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thanks!


https://github.com/user-attachments/assets/0348d225-933e-468f-9492-a80f850273ae

**Comment by fredericalpers** [comment]
@dai-eastgate The feature looks good so far, thank you for your work! However, I realize I might not have communicated clearly enough that this change needs to be applied not only to the address list but also to the address detail page. For this reason, I have updated the task/requirements accordingly.

Could you please make the necessary adjustments to apply the change to the address detail page as well?

**Comment by dai-eastgate** [comment]
> Could you please make the necessary adjustments to apply the change to the address detail page as well?

@fredericalpers I will update it

**Comment by dai-eastgate** [comment]
@fredericalpers  Please take a look at my demo video and let me know your opinions. Thanks!
In address list:

https://github.com/user-attachments/assets/61a30ff4-670e-445f-a1de-3a4f27f383ba

In address detail:

https://github.com/user-attachments/assets/616bacc0-e62a-4faf-9e74-848ca60fda1e

**Comment by fredericalpers** [comment]
@dai-eastgate thank you, looks good to me! Can I label this with "QA" and review it?

**Comment by dai-eastgate** [comment]
> @dai-eastgate thank you, looks good to me! Can I label this with "QA" and test/review it?

Sure, please help us review it.
