### ISSUE TITLE
Implementation of the “bildWebseite” field in property detail page settings

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#916]
# Implementation of the “bildWebseite” field in property detail page settings

### Introduction
There is a new system field “bildWebsite” for the address data records. The field can be activated in the administration.

Administration > Input fields > Module: Address management > Category: Administration

### User Story
As a user, I would like to be able to choose between the pass photo and the “bildWebsite” field on the property details page for the contact person (linked address data record of the broker type) so that I can display a corresponding high-resolution image for each address data record. The functionality of the “bildWebsite” field is to be implemented. 

Currently, the contact person image is defined by adding the “imageUrl” field in the field list. Similar to the selection of the image in address lists & detail pages, a new box “contact person image” is to be added. To avoid problems with backwards compatibility, the selection of the image should be transferred to the “Pass photo” checkbox.

### Task / Requirements

- [x] The new box “Ansprechpartner Bild” is to be added to the detailpage settings.
- [x] The system field “bildWebseite” is to be added to the detailpage settings.
- [x] Remove "User photo"
- [x]  The user can choose between the pass photo and the image of the website (from “bildWebseite”).
- [x] The pass photo should be selected by default because the image website field is not active by default in onOffice enterprise.

**Comment by yeneastgate** [comment]
@fredericalpers  Please help us confirm your requirements. Thank you!
> * The new box “Ansprechpartner Bild” is to be added to the detailpage settings.

Means:
We will add a new box as shown below:
![image](https://github.com/user-attachments/assets/ff5cf9d1-6ccb-412d-a525-d0439c4ddf8c)

Or we can add a new checkbox as follows:
![image](https://github.com/user-attachments/assets/4ecb3356-8dbc-4f97-8b9c-fdc1cb494b80)

**Comment by fredericalpers** [comment]
@yeneastgate "Contact Person Image" is supposed to go in the Photo Types checkbox. "User Photo" has to be removed. Thank you :)

**Comment by yeneastgate** [comment]
> @yeneastgate "Contact Person Image" is supposed to go in the Photo Types checkbox. "User Photo" has to be removed. Thank you :)

I got it, thanks!

**Comment by yeneastgate** [comment]
@fredericalpers Please watch my demo video and let me know your opinions.Thank you! 

https://github.com/user-attachments/assets/c70847e9-5b46-414d-a0d0-6f9905ea9906

**Comment by fredericalpers** [comment]
@yeneastgate It seems there was a misunderstanding. This Issue is related to the property detail page, but the change you made for the address detail page should actually be handled in this [Issue](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/914)

For the property detail page, the following needs to be done:

A new box called "Ansprechpartner Bild" should be created, allowing the selection between "Pass Foto" and "bildWebsite." As a result, the addition of the imageURL field from special fields should be removed and managed only through this new box. Please refer to the user story for more details.

Sorry for the inconvenience

**Comment by yeneastgate** [comment]
@fredericalpers Sorry for the confusion. I saw that you assigned the component to the 'address list detail page' and added 'Remove User photo,' which is only in the address detail. So I mistakenly thought it was the address detail. I will correct it.

**Comment by yeneastgate** [comment]
@fredericalpers Please watch my demo video and let me know your opinion about it. Thanks! 

https://github.com/user-attachments/assets/97857380-9a91-4f7d-87a1-08dfb0cb5d78

**Comment by fredericalpers** [comment]
@yeneastgate thank you, looks good to me! :) can I label this with "QA" and test/review it?

**Comment by yeneastgate** [comment]
> @yeneastgate thank you, looks good to me! :) can I label this with "QA" and test/review it?

Please help us review it. Thaks!
