### ISSUE TITLE
Display Link Fields as Actual Links in Frontend

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#920]
# Display Link Fields as Actual Links in Frontend

### Introduction
Currently, fields of the type "link" are displayed as plain text in the frontend, without functioning as actual clickable hyperlinks.

### User Story
As a user, I want link fields (e.g. Socialmedia) to be rendered as clickable hyperlinks in the frontend so that I can easily navigate to external resources by clicking on them. The links should open in a new tab to preserve my current browsing session, and security attributes should be added to prevent security vulnerabilities.

### Task / Requirements

- [x] Fields of the type "link" should be rendered as actual clickable hyperlinks (HTML <a> elements) in the frontend.
- [x] The target="_blank" attribute should be added to the rendered link, so that when a user clicks on it, the link opens in a new browser tab.
- [x] Add the rel="nofollow noopener" attributes to the rendered link to improve security.
- [x] Links should have proper aria-labels if necessary, to ensure screen readers announce the links appropriately.

**Comment by yeneastgate** [comment]
@fredericalpers 
Currently, I check on onOffice enterprise, the fields with "type = link" the API response is "type=text"
=> Please update the API to return the correct "type=link" for fields of the type "link"
![image](https://github.com/user-attachments/assets/d3fefdd7-d39c-4108-a2b2-9acad435c775)
![image](https://github.com/user-attachments/assets/aab98bd2-7365-4a89-83b0-fce166ede6b4)

**Comment by fredericalpers** [comment]
@yeneastgate please implement the the `<a>` and the attributes for the following fields:

Module: Contacts management Category: Contact
- [ ] Homepage

Module: Contacts management Category: Social media
- [ ] facebook
- [ ] twitter
- [ ] youtube
- [ ] instagram
- [ ] linkedin
- [ ] xing
- [ ] tiktok
- [ ] pinterest

Module: Contacts management Category: Administration:
- [ ] bewertungslinkWebseite

**Comment by yeneastgate** [comment]
> @yeneastgate please implement the the `<a>` and the attributes for the following fields:
> 
@fredericalpers  I got it, thanks!

**Comment by yeneastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thank you!


https://github.com/user-attachments/assets/72f79080-bfcc-4597-85af-ca97cd699ee7
