### ISSUE TITLE
Mandatory field marking and validation for the geo range search in the geoPosition field on the website

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#922]
# Mandatory field marking and validation for the geo range search in the geoPosition field on the website

### Introduction
There are some mandatory fields for the geoPositions field. These include country, radius and at least city or zip code. These mandatory fields are not declared and marked as mandatory fields in the frontend.

### User Story
We currently use the onOffice for WP-Websites plugin to display properties on our website. A central feature of our website is the geo range search in the geoPosition field, which allows visitors to search for properties based on location information. However, there is a problem: although the fields “Country”, “Area”, “City” and “Postcode” are defined as mandatory fields in the backend, this is not displayed correctly in the frontend. Users can leave the fields empty without being informed about missing entries, which leads to incomplete search queries.

In order for the geo range search to function optimally and for users to provide complete and accurate information, the relevant fields must be marked as mandatory fields and also be validated correctly in the frontend.

As a real estate agent, I would like the fields “Country”, “Area”, “City” and “Postcode” in the geolocation field of the area search to be marked with an asterix "*" as mandatory fields and displayed and validated accordingly in the frontend so that users can fill in this information correctly and completely.

Improving the geo range search by marking mandatory fields is crucial for the user-friendliness and success of the property search on the website.

### Task / Requirements

- [ ] The fields country, area, city and zip code in the geoposition field of the area search should be clearly marked as mandatory fields in the frontend. Each of these fields should be marked with an asterisk (*) to indicate that it is a mandatory field.
- [ ] If one of the mandatory fields remains empty, the search query may not be sent.
- [ ] An error message must be displayed informing the user that the mandatory field must be completed.

**Comment by yeneastgate** [comment]
@fredericalpers I would like to confirm some points with you
> * The fields country, area, city and zip code in the geoposition field of the area search should be clearly marked as mandatory fields in the frontend.

=>  When you refer to the "area" field, do you mean the "radius" field?


https://github.com/user-attachments/assets/6f636ebc-1405-4727-a4a1-7b81c8cba3a3


Note: If the fields “Country”, “Area”, “City” and “Postcode” are defined as mandatory fields in the backend, will all four fields become mandatory in the frontend? This means that old users who had previously checked all four fields in the admin will no longer be able to search by just three fields in the frontend.

**Comment by fredericalpers** [comment]
@yeneastgate Thank you I updated it to "radius" instead of area.

The fields country, radius, city and zip code in the geoposition field of the radius search should be clearly marked as mandatory fields in the frontend by using the asterix "*".

**Comment by yeneastgate** [comment]
@fredericalpers I've created PR for this issue. Please help us review it. Thanks!
