### ISSUE TITLE
Selection of redirection in the searchform.php to the target page

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#932]
# Selection of redirection in the searchform.php to the target page

### User Story
As an administrator or developer of a property website, I want to add a dropdown element in the settings page for the searchform.php that allows me to select a target page for search results. The selected page should automatically populate the form action attribute, so users are redirected to the correct property listing or results page without requiring manual code changes.

### Task/Requirements

- [ ] A dropdown (select element) should be integrated into the settings for the searchform.php to allow the administrator to choose between different target pages for search results.
- [ ] The dropdown must be implemented so that the selected target page automatically updates the action attribute of the search form.
- [ ] Once the user submits a search query on the frontend, they are redirected to the appropriate page without requiring any manual template modifications.

![searchform1](https://github.com/user-attachments/assets/e6df5726-9fc4-4cf4-a4a7-837db48f065a)

**Comment by yeneastgate** [comment]
@fredericalpers I see there's an old issue I've already investigated (see issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/613). Is this issue similar to that one?

**Comment by fredericalpers** [comment]
@yeneastgate you are right. the only difference is that this Issue here is "Step 1" without further additional changes to the behaviour besides the implementation of the forwarding. I will close the other issue, thank you :)

**Comment by fredericalpers** [comment]
@yeneastgate 

>In the "Select page" dropdown menu, will the list display "pages using shortcode" from the ListView?

We want to keep it simple and display all created pages.

>When a user submits a search query on the frontend, they will be redirected to the "selected page" in the admin panel, including the searched parameters in the search form and displaying the corresponding estate search results. 
>If the search form includes a "city" field but the selected page does not have a "city" field, the search should still function correctly based on the "city" field, even if the results are not shown in the estate information.

Correct, however the customer has to mark the fields as filterable/show in search on the searchform and the propertylist themselves. if the city field is not made filterable the search does not have to work with these fields.

>When searching in the search form, will the filters in "Filters & Records" depend on the Forwarding page? Because currently, if the "Filters & Records" of the search form and the "Filters & Records" of the Forwarding page are different, it will produce different results when searching.

Thats okay, since the customer has to make sure the searchform and the corresponding property lists are set up properly.

We simply want to give the customer the possibility to set up the forwarding with the form action without having to have coding knowledge and having to customize the templates.

**Comment by yeneastgate** [comment]
> We want to keep it simple and display all created pages.

@fredericalpers If it's the pages that have been created, will it display both the pages with the shortcode address and the form, right?

**Comment by yeneastgate** [comment]
![image](https://github.com/user-attachments/assets/6f55e69e-3769-486c-a8ea-7e25799b5535)

@fredericalpers Could you send me the link to the documentation so I can add it?

**Comment by fredericalpers** [comment]
@yeneastgate this is our current documentation: https://wp-plugin.onoffice.com/de/

**Comment by yeneastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thank you!

https://github.com/user-attachments/assets/c9e4e3ae-36f7-4dc3-a875-3a49c3e13b7e

**Comment by fredericalpers** [comment]
Seems good to me! I will review this as soon as possible! :) Thank you
