### ISSUE TITLE
Improved display of parking options on property pages (multiParkingLot)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#939]
# Improved display of parking options on property pages (multiParkingLot)

### User Story
Currently, the parking options in the property front-end template are displayed as simple text such as “2 carports at 10000 € each (purchase)”. This display is not very flexible and not user-friendly. Our goal is to create a more individual and user-friendly display of parking options based on actual data and to hide excess information such as prices of €0.

- Improvement of the user experience through an appealing and comprehensible presentation of the parking options.
- Reduce unnecessary information to increase the relevance of the display.

**Scenario 1 (with prices):**
2 Carport, 10,000 € (purchase), 3 Duplex, 300 € (rent)

**Scenario 2 (with and without price):**
2 carport, 1 garage, € 5,000 (purchase)

**Scenario 3 (without price):**
2 carport, 1 garage

### Task / Requirements

- [x] If the price of a parking space is 0.00, this price should not be displayed.
- [x] The marketing type (e.g. “purchase” or “rent”) should also not be displayed in this case.
- [x] Only if the price is greater than 0.00 should both the price and the marketing type (purchase or rent) be displayed.
- [x] The presentation of the parking options should be compact and yet informative.

**Comment by dai-eastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thanks! 

https://github.com/user-attachments/assets/88bd3dee-47a2-4542-ae72-bc4d3437f1dc

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! thank you :) I will review this as soon as possible.

**Comment by dai-eastgate** [comment]
> Can the prices also be displayed in currencies other than the euro?

@fredericalpers Yes, prices can be displayed in currencies other than the euro. 

> When changing the currency in enterprise to CHF the website frontend still displays Euro

If you are changing to CHF but it still shows euro, this usually happens when the "waehrung" field has not been added to the configuration. Please add it and let me know the results.

**Comment by fredericalpers** [comment]
@dai-eastgate Thank you for the update! However, from a user perspective, this implementation might not be ideal. Customers generally would not want to see an additional entry with "Currency: XX" in the list. Would it be possible to adjust this so that the configured value in Enterprise is used directly instead? This would create a cleaner experience for users.

**Comment by dai-eastgate** [comment]
@fredericalpers Are you suggesting that you want the correct currency to display without needing to configure the currency field?
1. When displaying parking, the currency  will not be shown even if it is configured.
2. If you only configure the currency field without displaying parking, the currency will still be shown.

Please clarify if this is what you meant!

**Comment by fredericalpers** [comment]
@dai-eastgate Currently I have to add the Currency field to be able to show the correct currency for the MultiParkingLot field. Ideally I do not have to add the extra currency field for the correct display on the MultiParkingLot field. 

![stellpl1](https://github.com/user-attachments/assets/a302ccdc-9969-4a22-944d-b94e356e36bd)
![stellpl2](https://github.com/user-attachments/assets/d2b407d0-796c-4bc0-aad5-e91fa31d0045)
![stellpl3](https://github.com/user-attachments/assets/68bac201-7bf0-4507-8e79-ce930c28cb80)

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed it. Please take a look at my demo video and let me know your opinions. Thanks! 

https://github.com/user-attachments/assets/19955967-cc3a-4dea-8ec2-0db86f3cbe9a

**Comment by fredericalpers** [comment]
Thank you, I will review this as soon as possible :)
