### ISSUE TITLE
Map for address list with pin display and show/hide functionality

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#948]
# Map for address list with pin display and show/hide functionality

### User Story
As a user of the address list, I would like to have a map view displayed above the address list, in which the locations of the data records are shown using pins. I would like to have the option of showing or hiding the map using a checkbox, similar to what is already possible in the property list, in order to get a better overview of the geographical distribution of the addresses

### Task / Requirements
- [x] A map (either Google Maps or OpenStreetMap) is displayed above the address list.
- [x] There is a checkbox in "Layout & Design" that can be used to show and hide the map.
- [x] By clicking on a pin, details of the data record are displayed in a small pop-up. These details include: First name, last name, Company name
- [x] The map is implemented and tested in both the plugin and the default template.
- [x] The map is responsive and adapts to different screen sizes (desktop, tablet, mobile device).

The map is based on the already implemented map function of the real property list, so that users who are familiar with this function can expect similar operation and user-friendliness.

![adressmap](https://github.com/user-attachments/assets/3e2d0cf7-1fc4-4a5f-b676-5364922f2b6d)
![map123](https://github.com/user-attachments/assets/7bd54ba9-b2d4-49fc-a987-765d2b673ff7)

**Comment by fredericalpers** [comment]
@yeneastgate thank you, we will review this as soon as possible :)
